Prediction of Housing Values in Boston
================

**File name:** “housing.proper.csv” (given in the problem set) has
housing values in the suburbs of Boston

  - **506 observations** and **13 predictor variables** (independent
    variables or X or features)  
  - Median price is a more accurate measure of market prices as it is
    not affected by
    outliers

<!-- end list -->

``` r
library (tidyverse)  
```

    ## ── Attaching packages ───────────────────────────────────────────────────── tidyverse 1.3.0 ──

    ## ✔ ggplot2 3.3.0     ✔ purrr   0.3.3
    ## ✔ tibble  2.1.3     ✔ dplyr   0.8.3
    ## ✔ tidyr   1.0.0     ✔ stringr 1.4.0
    ## ✔ readr   1.3.1     ✔ forcats 0.4.0

    ## ── Conflicts ──────────────────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library (ggplot2)  
library(corrplot)
```

    ## corrplot 0.84 loaded

``` r
library(MASS)
```

    ## 
    ## Attaching package: 'MASS'

    ## The following object is masked from 'package:dplyr':
    ## 
    ##     select

``` r
library(dplyr)
library(broom)
library (car)
```

    ## Loading required package: carData

    ## 
    ## Attaching package: 'car'

    ## The following object is masked from 'package:dplyr':
    ## 
    ##     recode

    ## The following object is masked from 'package:purrr':
    ## 
    ##     some

``` r
housing_data = read.csv("housing.proper.csv") #loading the dataset
housing_data_df= data.frame(housing_data)
colnames(housing_data_df) <- c("X1","X2","X3","X4","X5","X6","X7","X8",
                            "X9","X10","X11","X12","X13", "Y") #transforming column names
lnY = log(housing_data_df$Y)
```

# Exploratory Data Analysis

**Objective of EDA** : To choose important variables or features of this
dataset Visualisations are used the explain relationship between
features and target variable

**Split the data into 70% training set (model building data set) and 30%
testing set**

``` r
set.seed(1234) #set seed to ensure same random numbers are generated
require(caTools)
```

    ## Loading required package: caTools

``` r
sample = sample.split(housing_data_df, SplitRatio = 0.7)
#Splits the dataset "housing_data" in the ratio mentioned. Marks rows as logical true and remaining as logical false.  

training_housing_data = subset(housing_data_df, sample == TRUE)  #creates training dataset with rows marked true
lny = log(training_housing_data$Y)
testing_housing_data = subset(housing_data_df, sample ==FALSE)
lny_testing = log(testing_housing_data$Y)
```

**Choosing features through Summary Statistics, Correlation Plot, Heat
Map and Boxplot**

EDA is performed on the complete
dataset

``` r
summary (housing_data_df) # to get statistic of each variable to detect outliers  
```

    ##        X1                 X2               X3              X4         
    ##  Min.   : 0.00632   Min.   :  0.00   Min.   : 0.46   Min.   :0.00000  
    ##  1st Qu.: 0.08204   1st Qu.:  0.00   1st Qu.: 5.19   1st Qu.:0.00000  
    ##  Median : 0.25651   Median :  0.00   Median : 9.69   Median :0.00000  
    ##  Mean   : 3.61352   Mean   : 11.36   Mean   :11.14   Mean   :0.06917  
    ##  3rd Qu.: 3.67708   3rd Qu.: 12.50   3rd Qu.:18.10   3rd Qu.:0.00000  
    ##  Max.   :88.97620   Max.   :100.00   Max.   :27.74   Max.   :1.00000  
    ##        X5               X6              X7               X8        
    ##  Min.   :0.3850   Min.   :3.561   Min.   :  2.90   Min.   : 1.130  
    ##  1st Qu.:0.4490   1st Qu.:5.886   1st Qu.: 45.02   1st Qu.: 2.100  
    ##  Median :0.5380   Median :6.208   Median : 77.50   Median : 3.207  
    ##  Mean   :0.5547   Mean   :6.285   Mean   : 68.57   Mean   : 3.795  
    ##  3rd Qu.:0.6240   3rd Qu.:6.623   3rd Qu.: 94.08   3rd Qu.: 5.188  
    ##  Max.   :0.8710   Max.   :8.780   Max.   :100.00   Max.   :12.127  
    ##        X9              X10             X11             X12        
    ##  Min.   : 1.000   Min.   :187.0   Min.   :12.60   Min.   :  0.32  
    ##  1st Qu.: 4.000   1st Qu.:279.0   1st Qu.:17.40   1st Qu.:375.38  
    ##  Median : 5.000   Median :330.0   Median :19.05   Median :391.44  
    ##  Mean   : 9.549   Mean   :408.2   Mean   :18.46   Mean   :356.67  
    ##  3rd Qu.:24.000   3rd Qu.:666.0   3rd Qu.:20.20   3rd Qu.:396.23  
    ##  Max.   :24.000   Max.   :711.0   Max.   :22.00   Max.   :396.90  
    ##       X13              Y        
    ##  Min.   : 1.73   Min.   : 5.00  
    ##  1st Qu.: 6.95   1st Qu.:17.02  
    ##  Median :11.36   Median :21.20  
    ##  Mean   :12.65   Mean   :22.53  
    ##  3rd Qu.:16.95   3rd Qu.:25.00  
    ##  Max.   :37.97   Max.   :50.00

``` r
housing_data.cor = round(cor(housing_data_df), 3) #correlation between features and median housing values
housing_data.cor
```

    ##         X1     X2     X3     X4     X5     X6     X7     X8     X9    X10
    ## X1   1.000 -0.200  0.407 -0.056  0.421 -0.219  0.353 -0.380  0.626  0.583
    ## X2  -0.200  1.000 -0.534 -0.043 -0.517  0.312 -0.570  0.664 -0.312 -0.315
    ## X3   0.407 -0.534  1.000  0.063  0.764 -0.392  0.645 -0.708  0.595  0.721
    ## X4  -0.056 -0.043  0.063  1.000  0.091  0.091  0.087 -0.099 -0.007 -0.036
    ## X5   0.421 -0.517  0.764  0.091  1.000 -0.302  0.731 -0.769  0.611  0.668
    ## X6  -0.219  0.312 -0.392  0.091 -0.302  1.000 -0.240  0.205 -0.210 -0.292
    ## X7   0.353 -0.570  0.645  0.087  0.731 -0.240  1.000 -0.748  0.456  0.506
    ## X8  -0.380  0.664 -0.708 -0.099 -0.769  0.205 -0.748  1.000 -0.495 -0.534
    ## X9   0.626 -0.312  0.595 -0.007  0.611 -0.210  0.456 -0.495  1.000  0.910
    ## X10  0.583 -0.315  0.721 -0.036  0.668 -0.292  0.506 -0.534  0.910  1.000
    ## X11  0.290 -0.392  0.383 -0.122  0.189 -0.356  0.262 -0.232  0.465  0.461
    ## X12 -0.385  0.176 -0.357  0.049 -0.380  0.128 -0.274  0.292 -0.444 -0.442
    ## X13  0.456 -0.413  0.604 -0.054  0.591 -0.614  0.602 -0.497  0.489  0.544
    ## Y   -0.388  0.360 -0.484  0.175 -0.427  0.695 -0.377  0.250 -0.382 -0.469
    ##        X11    X12    X13      Y
    ## X1   0.290 -0.385  0.456 -0.388
    ## X2  -0.392  0.176 -0.413  0.360
    ## X3   0.383 -0.357  0.604 -0.484
    ## X4  -0.122  0.049 -0.054  0.175
    ## X5   0.189 -0.380  0.591 -0.427
    ## X6  -0.356  0.128 -0.614  0.695
    ## X7   0.262 -0.274  0.602 -0.377
    ## X8  -0.232  0.292 -0.497  0.250
    ## X9   0.465 -0.444  0.489 -0.382
    ## X10  0.461 -0.442  0.544 -0.469
    ## X11  1.000 -0.177  0.374 -0.508
    ## X12 -0.177  1.000 -0.366  0.333
    ## X13  0.374 -0.366  1.000 -0.738
    ## Y   -0.508  0.333 -0.738  1.000

``` r
heatmap(housing_data.cor, Rowv = NA, Colv = NA)
```

![](Prediction-of-Housing-Values-in-Boston_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

``` r
corrplot(cor(housing_data_df), method = "number", type = "upper", diag = FALSE)
```

![](Prediction-of-Housing-Values-in-Boston_files/figure-gfm/unnamed-chunk-3-2.png)<!-- -->

**Removing Charles River Dummy Variable (X4)** as the Correlation
between Median House Value and X4 is low (0.18). Smaller value of
correlation signifies that the presence of Charles River has little to
no impact on the value median value of houses.

Strong positive correlation (0.91) between X9 (index of accessibility to
radial highways) and X10 (full-value property-tax rate per 10,000)
suggests Multicollinearity, which means we can drop one variable with a
lower correlation with Y. Here, higher accessibility to radial highways
is connected to a high tax value of a property. **I will drop X9 (index
of accessibility to radial highways)** as it has a lower correlation
with median housing values as compared to X10 (full-value property-tax
rate per 10,000). **X9 is a repetitive predictor.**

Strong Negative correlation (-0.75) between X7 (proportion of owner
occupied units built prior to 1940) and X8 (weighted distances to five
Boston employment
centres)

``` r
housing_data.box = boxplot(housing_data_df, xlab= "Features", ylab ="Frequency") #boxplot to detect outliers 
```

![](Prediction-of-Housing-Values-in-Boston_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->
There are outliers in **X1(per capita crime rate by town)**,
**X2(proportion of residential land zoned for lots over 25,000 sq.ft.)**
and **X12 (proportion of African Americans by town)**

There is high variability in **X10 (full-value property-tax rate per
10,000)**

Plotting the model generates 4 plots: Normal QQ plot. Resdiuals vs
Fitted. Scale vs Location. Residuals vs
Leverage.

``` r
full_housing_model =lm(Y~X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10 + X11 + X12 + X13 ,data=housing_data_df)
log_full_housing_model =lm(lnY~X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10 + X11 + X12 + X13 ,data=housing_data_df)


summary(full_housing_model)
```

    ## 
    ## Call:
    ## lm(formula = Y ~ X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + 
    ##     X10 + X11 + X12 + X13, data = housing_data_df)
    ## 
    ## Residuals:
    ##     Min      1Q  Median      3Q     Max 
    ## -15.595  -2.730  -0.518   1.777  26.199 
    ## 
    ## Coefficients:
    ##               Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)  3.646e+01  5.103e+00   7.144 3.28e-12 ***
    ## X1          -1.080e-01  3.286e-02  -3.287 0.001087 ** 
    ## X2           4.642e-02  1.373e-02   3.382 0.000778 ***
    ## X3           2.056e-02  6.150e-02   0.334 0.738288    
    ## X4           2.687e+00  8.616e-01   3.118 0.001925 ** 
    ## X5          -1.777e+01  3.820e+00  -4.651 4.25e-06 ***
    ## X6           3.810e+00  4.179e-01   9.116  < 2e-16 ***
    ## X7           6.922e-04  1.321e-02   0.052 0.958229    
    ## X8          -1.476e+00  1.995e-01  -7.398 6.01e-13 ***
    ## X9           3.060e-01  6.635e-02   4.613 5.07e-06 ***
    ## X10         -1.233e-02  3.760e-03  -3.280 0.001112 ** 
    ## X11         -9.527e-01  1.308e-01  -7.283 1.31e-12 ***
    ## X12          9.312e-03  2.686e-03   3.467 0.000573 ***
    ## X13         -5.248e-01  5.072e-02 -10.347  < 2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 4.745 on 492 degrees of freedom
    ## Multiple R-squared:  0.7406, Adjusted R-squared:  0.7338 
    ## F-statistic: 108.1 on 13 and 492 DF,  p-value: < 2.2e-16

``` r
tidy(full_housing_model) %>% arrange(p.value)
```

    ## # A tibble: 14 x 5
    ##    term          estimate std.error statistic  p.value
    ##    <chr>            <dbl>     <dbl>     <dbl>    <dbl>
    ##  1 X13          -0.525      0.0507   -10.3    7.78e-23
    ##  2 X6            3.81       0.418      9.12   1.98e-18
    ##  3 X8           -1.48       0.199     -7.40   6.01e-13
    ##  4 X11          -0.953      0.131     -7.28   1.31e-12
    ##  5 (Intercept)  36.5        5.10       7.14   3.28e-12
    ##  6 X5          -17.8        3.82      -4.65   4.25e- 6
    ##  7 X9            0.306      0.0663     4.61   5.07e- 6
    ##  8 X12           0.00931    0.00269    3.47   5.73e- 4
    ##  9 X2            0.0464     0.0137     3.38   7.78e- 4
    ## 10 X1           -0.108      0.0329    -3.29   1.09e- 3
    ## 11 X10          -0.0123     0.00376   -3.28   1.11e- 3
    ## 12 X4            2.69       0.862      3.12   1.93e- 3
    ## 13 X3            0.0206     0.0615     0.334  7.38e- 1
    ## 14 X7            0.000692   0.0132     0.0524 9.58e- 1

``` r
plot(log_full_housing_model)
```

![](Prediction-of-Housing-Values-in-Boston_files/figure-gfm/unnamed-chunk-5-1.png)<!-- -->![](Prediction-of-Housing-Values-in-Boston_files/figure-gfm/unnamed-chunk-5-2.png)<!-- -->![](Prediction-of-Housing-Values-in-Boston_files/figure-gfm/unnamed-chunk-5-3.png)<!-- -->![](Prediction-of-Housing-Values-in-Boston_files/figure-gfm/unnamed-chunk-5-4.png)<!-- -->

``` r
pairs(housing_data_df)
```

![](Prediction-of-Housing-Values-in-Boston_files/figure-gfm/unnamed-chunk-5-5.png)<!-- -->

``` r
#We have already removed X9 due to multicollinearity with X10, another reason to remove it is it's *high p-value*. 
#We will remove X8 too as it has the highest p-value as compared to all the other variables. High p-value suggests changes in X8 are not associated with changes in Y (median housing values)
```

We remove every variable with a pvalue greater than 0.05.  
Through EDA we have removed 4 variables (X3, X4, X7, X9, X12)  
Since X13 has the smallest p-value it becomes the first step for Forward
Stepwise Selection

# Model Selection and Validation

Fitting the model with selected
variables

``` r
log_full_housing_model =lm(lny~X1 + X2 + X5 + X6 + X8 + X10 + X11 + X13 ,data=training_housing_data)
s <- summary(log_full_housing_model)$sigma
# Selection criteria for the full model
SSres <- sum(log_full_housing_model$residuals^2)
Rsq <- summary(log_full_housing_model$r.squared)
Rsq_adj <- summary(log_full_housing_model)$adj.r.squared
p_prime <- length(log_full_housing_model$coefficients)
n <- nrow(training_housing_data)
C <- SSres/s^2 + 2*p_prime - n
AIC <- n*log(SSres) - n*log(n) + 2*p_prime


# Function that returns the selection criteria
select_criteria = function(model, n, s)
{
  SSres <- sum(model$residuals^2)
  Rsq <- summary(model)$r.squared
  Rsq_adj <- summary(model)$adj.r.squared
  p_prime <- length(model$coefficients)
  C <- SSres/s^2 + 2*p_prime - n
  AIC <- n*log(SSres) - n*log(n) + 2*p_prime
  res <- c(SSres, Rsq, Rsq_adj, C, AIC)
  names(res) <- c("SSres", "Rsq", "Rsq_adj", "C", "AIC")
  return(res)
}



rbind(
  select_criteria(lm(lny~X1+X2, data = training_housing_data), n, s),
  select_criteria(lm(lny~X1+X2+X6, data = training_housing_data), n, s),
  select_criteria(lm(lny~X1+X2+X3+X6+X8, data = training_housing_data), n, s),
  select_criteria(lm(lny~X1+X2+X5+X6+X8, data = training_housing_data), n, s),
  select_criteria(lm(lny~X1+X2+X3+X6+X9, data = training_housing_data), n, s),
  select_criteria(lm(lny~X1+X2+X5+X6+X8+X10, data = training_housing_data), n, s),
  select_criteria(lm(lny~X1+X2+X5+X6+X8+X10+X11, data = training_housing_data), n, s),
  select_criteria(lm(lny~X1+X2+X5+X6+X8+X10+X11+X13, data = training_housing_data), n, s),
  select_criteria(lm(lny~X1+X2+X3+X5+X6+X8+X10+X11+X13, data = training_housing_data), n, s))
```

    ##          SSres       Rsq   Rsq_adj         C        AIC
    ##  [1,] 34.04853 0.3386797 0.3345848 621.56550  -730.4700
    ##  [2,] 21.26331 0.5870054 0.5831576 270.00777  -881.9520
    ##  [3,] 19.74294 0.6165353 0.6105437 231.96399  -902.1370
    ##  [4,] 19.02593 0.6304617 0.6246877 212.13605  -914.1968
    ##  [5,] 19.84237 0.6146041 0.6085823 234.71358  -900.4993
    ##  [6,] 18.28503 0.6448521 0.6381722 193.64751  -925.1455
    ##  [7,] 16.57020 0.6781591 0.6710746 148.22610  -955.2491
    ##  [8,] 11.46323 0.7773511 0.7717322   9.00000 -1073.3673
    ##  [9,] 11.45943 0.7774250 0.7710859  10.89471 -1071.4756

``` r
sum((lny) - mean(lny)^2)
```

    ## [1] -2004.703

Model lny~X1+X2+X5+X6+X8+X10+X11+X13 has  
\- **Coefficient of Determination 0.777 and Adjusted coefficient of
determination is 0.771**. Adding more variables in the next model causes
a very minute change in both. Therefore, the current model is correct  
\- the smallest **Akaike’s Information Criterion, (AIC: -1073)**  
\- **Mallows’ Cp** is close to p’and is equal to **9**

\`\`\` We validate the reduced model against the boston housing testing
set and find that **Mean squared prediction error** (MSPE) & MSRes are
quite closer together indicating a good predictive ability of the
model.

# Model Validation

``` r
#fit_model_building <- lm(lny~X1+X2+X5+X6+X8+X10+X11+X13, data = training_housing_data) 
fit_validation <- lm(lny_testing~X1+X2+X5+X6+X8+X10+X11+X13, data = testing_housing_data) 
#surgic_valid <- read.csv("CH09TA05.txt", sep = "", header = FALSE)
#newx <- surgic_valid[,c(1, 2, 3)]
#colnames(newx) <- c("X1","X2","X3")
Y_pred <- predict(fit_validation)

Y_obs <- (testing_housing_data$Y)
n_star <- nrow(testing_housing_data)
MSPE <- sum( (Y_obs-Y_pred)^2/n_star ) #Mean Squared Prediction Error should be small
print(MSPE)
```

    ## [1] 480.1425

``` r
MS_res <- (summary(fit_validation)$sigma)^2
print(MS_res)
```

    ## [1] 0.04711715

``` r
sum((training_housing_data$lny - predict(fit_validation))^2)
```

    ## [1] 0

# Diagnostics

  - Outlying Y observations
  - Outlying X observations
  - Influential observations
  - Multicollinearity

<!-- end list -->

``` r
fit1 <- lm(Y ~ X1+X2+X5+X6+X8+X10+X11+X13, data = housing_data_df)
# Outlying Y observations

# Statistical test
outlierTest(fit1)
```

    ##     rstudent unadjusted p-value Bonferroni p
    ## 369 5.915813         6.1600e-09   3.1170e-06
    ## 373 5.808881         1.1251e-08   5.6930e-06
    ## 372 5.464332         7.3674e-08   3.7279e-05
    ## 370 4.357304         1.6012e-05   8.1022e-03
    ## 371 3.941422         9.2638e-05   4.6875e-02

``` r
# Studentized deleted residuals
t <- rstudent(fit1)
alpha <- 0.05
n <- length(lnY)
p_prime = length(coef(fit1)) 
t_crit <- qt(1-alpha/(2*n),n-p_prime-1)
round(t,2)
```

    ##     1     2     3     4     5     6     7     8     9    10    11    12    13 
    ## -1.47 -0.74  0.72  0.94  1.66  0.71  0.04  1.66  1.22  0.08 -0.73 -0.47  0.24 
    ##    14    15    16    17    18    19    20    21    22    23    24    25    26 
    ##  0.05 -0.37  0.00  0.37  0.02  0.53 -0.15  0.16  0.30 -0.20  0.09 -0.09 -0.12 
    ##    27    28    29    30    31    32    33    34    35    36    37    38    39 
    ##  0.12 -0.22 -0.37 -0.15  0.16 -0.86  0.58 -0.36 -0.38 -0.95 -0.45 -0.38  0.40 
    ##    40    41    42    43    44    45    46    47    48    49    50    51    52 
    ## -0.10  0.11 -0.32  0.03  0.05 -0.30 -0.48  0.02 -0.17  1.34  0.58 -0.15 -0.57 
    ##    53    54    55    56    57    58    59    60    61    62    63    64    65 
    ## -0.45  0.01  0.31  1.07 -0.17 -0.11  0.53 -0.05  0.46 -0.26 -0.15  0.71  2.03 
    ##    66    67    68    69    70    71    72    73    74    75    76    77    78 
    ## -1.46 -1.24  0.05 -0.08 -0.10 -0.31 -0.08 -0.43 -0.23 -0.51 -0.75 -0.82 -0.72 
    ##    79    80    81    82    83    84    85    86    87    88    89    90    91 
    ## -0.20 -0.61 -0.13 -0.65 -0.26 -0.45 -0.19 -0.29  0.10 -0.75 -1.63 -0.63 -1.06 
    ##    92    93    94    95    96    97    98    99   100   101   102   103   104 
    ## -1.25 -1.17 -0.77 -1.22 -0.29 -0.80  0.34  1.51 -0.02  0.32 -0.10 -1.10 -0.42 
    ##   105   106   107   108   109   110   111   112   113   114   115   116   117 
    ## -0.50  0.02  0.31 -0.29 -0.82 -0.29 -0.01 -1.02 -0.59 -0.59 -1.61 -0.72 -0.67 
    ##   118   119   120   121   122   123   124   125   126   127   128   129   130 
    ## -1.14 -0.28 -0.50  0.16 -0.33  0.13  0.37 -0.21 -0.09  0.41 -0.13 -0.57 -0.27 
    ##   131   132   133   134   135   136   137   138   139   140   141   142   143 
    ## -0.57 -0.36  0.17  0.17 -0.11 -0.20 -0.07 -0.85 -0.43 -0.07 -0.25  1.95  0.19 
    ##   144   145   146   147   148   149   150   151   152   153   154   155   156 
    ##  0.59  0.57 -0.21 -0.67  1.19  1.51 -0.12 -0.13 -0.03 -0.72 -0.02 -0.92 -1.20 
    ##   157   158   159   160   161   162   163   164   165   166   167   168   169 
    ## -0.87  1.34 -1.23 -0.82 -0.93  2.39  2.17  1.89 -0.57 -0.54  2.27 -0.31 -0.89 
    ##   170   171   172   173   174   175   176   177   178   179   180   181   182 
    ## -1.19 -1.37 -1.29  0.11 -1.11 -0.77 -0.31 -0.46 -0.93 -0.35  0.92  1.06  1.84 
    ##   183   184   185   186   187   188   189   190   191   192   193   194   195 
    ##  0.85  0.38  0.92  1.11  2.89 -0.48 -0.74 -0.13  1.04 -0.15  0.48 -0.32 -0.64 
    ##   196   197   198   199   200   201   202   203   204   205   206   207   208 
    ##  1.94 -0.74 -0.69 -0.18  0.68  0.12 -1.23  0.80  1.49  1.54  0.01  0.15  1.01 
    ##   209   210   211   212   213   214   215   216   217   218   219   220   221 
    ##  0.75  1.30  0.47  1.15  0.53  0.56  2.68  0.10  0.01  0.14  0.02 -0.72 -0.64 
    ##   222   223   224   225   226   227   228   229   230   231   232   233   234 
    ##  0.38 -0.27  0.22  1.33  2.09  0.03 -0.10  2.32  0.14  0.13 -0.27  0.75  2.29 
    ##   235   236   237   238   239   240   241   242   243   244   245   246   247 
    ##  0.07 -0.10 -0.33 -0.17 -0.89 -0.96 -0.97 -0.58 -0.29 -0.70  0.36  1.21  0.95 
    ##   248   249   250   251   252   253   254   255   256   257   258   259   260 
    ##  0.19  0.69  0.47  0.08 -0.05  0.95  2.62 -0.59 -0.29  1.37  1.34 -0.07 -0.93 
    ##   261   262   263   264   265   266   267   268   269   270   271   272   273 
    ## -0.14  1.24  1.58 -0.63  0.18 -0.96 -0.02  1.89  0.88 -0.36 -0.14 -0.35 -0.79 
    ##   274   275   276   277   278   279   280   281   282   283   284   285   286 
    ##  0.46 -0.17 -0.33  0.07  0.23 -0.18  0.17  1.49  0.41  1.83  1.69  0.00 -1.24 
    ##   287   288   289   290   291   292   293   294   295   296   297   298   299 
    ## -0.09 -0.61 -0.83 -0.31 -0.94  0.66 -0.71 -0.34 -0.49  0.03 -0.04  0.27 -1.44 
    ##   300   301   302   303   304   305   306   307   308   309   310   311   312 
    ## -0.71 -1.28 -1.29 -0.41  0.12  0.84 -0.19 -0.20 -0.64 -1.32 -0.73 -0.60 -1.07 
    ##   313   314   315   316   317   318   319   320   321   322   323   324   325 
    ## -0.84 -0.89 -0.44 -0.91  0.02  0.28 -0.32 -0.12 -0.23 -0.37 -0.49 -0.15 -0.04 
    ##   326   327   328   329   330   331   332   333   334   335   336   337   338 
    ## -0.05 -0.15  0.62 -0.74 -0.75 -0.76 -0.73 -1.05  0.11 -0.07  0.24  0.02  0.00 
    ##   339   340   341   342   343   344   345   346   347   348   349   350   351 
    ## -0.18 -0.31 -0.41  0.27 -1.69 -0.92  0.35 -0.05  0.23 -0.56 -0.58  0.53  0.16 
    ##   352   353   354   355   356   357   358   359   360   361   362   363   364 
    ##  0.39  0.11  1.31  0.70  0.68  0.40  0.59  0.90  0.95  0.66  0.38  0.79  0.06 
    ##   365   366   367   368   369   370   371   372   373   374   375   376   377 
    ## -2.69  3.15  1.51  2.45  5.92  4.36  3.94  5.46  5.81  2.05  3.21 -1.96 -0.58 
    ##   378   379   380   381   382   383   384   385   386   387   388   389   390 
    ## -1.13 -0.31 -1.08 -1.14 -1.28 -0.07  0.22  1.33  0.20  1.25  0.73  1.13 -0.20 
    ##   391   392   393   394   395   396   397   398   399   400   401   402   403 
    ## -0.11  1.49  0.35 -1.03 -0.79 -1.20 -1.08 -1.27 -0.06 -0.67 -1.01 -1.89 -1.00 
    ##   404   405   406   407   408   409   410   411   412   413   414   415   416 
    ## -0.69  0.32 -0.68  1.13  1.78  0.97  1.42 -0.75 -0.35  3.12  0.86  2.09 -0.89 
    ##   417   418   419   420   421   422   423   424   425   426   427   428   429 
    ## -1.62  0.51 -0.21 -1.67 -0.49 -0.65  0.57 -0.34 -0.99 -0.75 -1.65 -1.26 -0.91 
    ##   430   431   432   433   434   435   436   437   438   439   440   441   442 
    ## -1.04 -1.02 -1.24 -1.39 -0.84 -1.19 -0.26 -1.47 -0.46  0.47  0.28 -0.21  0.21 
    ##   443   444   445   446   447   448   449   450   451   452   453   454   455 
    ##  0.21 -0.30 -0.13 -0.42 -0.43 -0.88 -0.41 -0.75 -1.12 -0.66 -0.23 -0.78 -0.56 
    ##   456   457   458   459   460   461   462   463   464   465   466   467   468 
    ## -0.72 -0.40 -0.32 -0.43  0.59 -0.54 -0.23  0.21 -0.22  0.50  0.62  0.57  0.70 
    ##   469   470   471   472   473   474   475   476   477   478   479   480   481 
    ##  0.68  0.62  0.29 -0.35  0.46  1.07 -0.24 -0.37 -0.45  0.38 -0.66  0.14  0.22 
    ##   482   483   484   485   486   487   488   489   490   491   492   493   494 
    ## -0.43 -0.49  0.49  0.53  0.08  0.21  0.16 -0.23 -1.22 -0.06 -0.98 -0.11  0.10 
    ##   495   496   497   498   499   500   501   502   503   504   505   506 
    ##  0.64  1.15  1.09 -0.29 -0.17 -0.31 -0.89 -0.50 -0.59 -1.06 -1.13 -2.38

``` r
t_crit
```

    ## [1] 3.925428

``` r
which(abs(t) > t_crit)
```

    ## 369 370 371 372 373 
    ## 369 370 371 372 373

``` r
# Outlying X observations 
Pii <- hatvalues(fit1)
round(Pii, 2)
```

    ##    1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16 
    ## 0.01 0.01 0.01 0.01 0.02 0.01 0.01 0.02 0.05 0.02 0.03 0.02 0.01 0.01 0.01 0.01 
    ##   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32 
    ## 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.02 0.01 
    ##   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48 
    ## 0.03 0.01 0.01 0.01 0.01 0.01 0.01 0.03 0.03 0.01 0.01 0.01 0.01 0.01 0.01 0.02 
    ##   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64 
    ## 0.04 0.01 0.01 0.01 0.01 0.01 0.03 0.03 0.03 0.03 0.02 0.01 0.01 0.01 0.01 0.02 
    ##   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80 
    ## 0.03 0.03 0.03 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 
    ##   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96 
    ## 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 
    ##   97   98   99  100  101  102  103  104  105  106  107  108  109  110  111  112 
    ## 0.01 0.02 0.02 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 
    ##  113  114  115  116  117  118  119  120  121  122  123  124  125  126  127  128 
    ## 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.02 0.02 0.02 0.03 0.02 0.02 0.03 0.01 
    ##  129  130  131  132  133  134  135  136  137  138  139  140  141  142  143  144 
    ## 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.02 0.04 0.04 0.04 
    ##  145  146  147  148  149  150  151  152  153  154  155  156  157  158  159  160 
    ## 0.05 0.04 0.04 0.05 0.04 0.04 0.04 0.05 0.05 0.04 0.04 0.04 0.04 0.02 0.02 0.05 
    ##  161  162  163  164  165  166  167  168  169  170  171  172  173  174  175  176 
    ## 0.02 0.02 0.02 0.03 0.02 0.02 0.02 0.02 0.01 0.01 0.01 0.02 0.01 0.01 0.01 0.01 
    ##  177  178  179  180  181  182  183  184  185  186  187  188  189  190  191  192 
    ## 0.01 0.01 0.01 0.01 0.02 0.01 0.01 0.01 0.01 0.01 0.02 0.02 0.02 0.02 0.01 0.01 
    ##  193  194  195  196  197  198  199  200  201  202  203  204  205  206  207  208 
    ## 0.01 0.01 0.01 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.04 0.05 0.01 0.00 0.01 
    ##  209  210  211  212  213  214  215  216  217  218  219  220  221  222  223  224 
    ## 0.01 0.02 0.01 0.02 0.01 0.00 0.03 0.01 0.01 0.01 0.01 0.01 0.01 0.02 0.01 0.01 
    ##  225  226  227  228  229  230  231  232  233  234  235  236  237  238  239  240 
    ## 0.02 0.03 0.02 0.01 0.01 0.01 0.01 0.01 0.02 0.02 0.01 0.01 0.01 0.01 0.01 0.01 
    ##  241  242  243  244  245  246  247  248  249  250  251  252  253  254  255  256 
    ## 0.01 0.01 0.01 0.01 0.02 0.02 0.01 0.01 0.01 0.01 0.01 0.01 0.03 0.05 0.02 0.03 
    ##  257  258  259  260  261  262  263  264  265  266  267  268  269  270  271  272 
    ## 0.03 0.04 0.02 0.02 0.02 0.02 0.03 0.02 0.02 0.03 0.02 0.03 0.02 0.01 0.01 0.01 
    ##  273  274  275  276  277  278  279  280  281  282  283  284  285  286  287  288 
    ## 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.02 0.01 0.01 0.04 0.03 0.01 0.03 0.01 
    ##  289  290  291  292  293  294  295  296  297  298  299  300  301  302  303  304 
    ## 0.01 0.01 0.04 0.04 0.04 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.01 0.01 0.01 
    ##  305  306  307  308  309  310  311  312  313  314  315  316  317  318  319  320 
    ## 0.01 0.01 0.02 0.02 0.01 0.01 0.02 0.01 0.01 0.01 0.00 0.01 0.01 0.01 0.00 0.00 
    ##  321  322  323  324  325  326  327  328  329  330  331  332  333  334  335  336 
    ## 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.02 0.02 0.02 0.01 0.01 0.02 0.02 0.02 
    ##  337  338  339  340  341  342  343  344  345  346  347  348  349  350  351  352 
    ## 0.01 0.01 0.01 0.01 0.01 0.01 0.02 0.01 0.01 0.02 0.03 0.03 0.02 0.02 0.02 0.04 
    ##  353  354  355  356  357  358  359  360  361  362  363  364  365  366  367  368 
    ## 0.04 0.05 0.05 0.05 0.01 0.02 0.02 0.02 0.03 0.02 0.03 0.02 0.05 0.09 0.02 0.05 
    ##  369  370  371  372  373  374  375  376  377  378  379  380  381  382  383  384 
    ## 0.05 0.02 0.02 0.02 0.02 0.03 0.04 0.02 0.01 0.01 0.02 0.01 0.27 0.01 0.01 0.01 
    ##  385  386  387  388  389  390  391  392  393  394  395  396  397  398  399  400 
    ## 0.02 0.02 0.02 0.02 0.02 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.04 0.02 
    ##  401  402  403  404  405  406  407  408  409  410  411  412  413  414  415  416 
    ## 0.02 0.01 0.01 0.02 0.04 0.14 0.03 0.02 0.02 0.02 0.09 0.02 0.03 0.03 0.07 0.02 
    ##  417  418  419  420  421  422  423  424  425  426  427  428  429  430  431  432 
    ## 0.02 0.02 0.17 0.02 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.04 0.01 0.01 0.01 0.02 
    ##  433  434  435  436  437  438  439  440  441  442  443  444  445  446  447  448 
    ## 0.01 0.01 0.01 0.02 0.01 0.01 0.03 0.01 0.01 0.01 0.01 0.01 0.01 0.02 0.01 0.01 
    ##  449  450  451  452  453  454  455  456  457  458  459  460  461  462  463  464 
    ## 0.01 0.01 0.01 0.01 0.01 0.02 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.02 
    ##  465  466  467  468  469  470  471  472  473  474  475  476  477  478  479  480 
    ## 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.02 0.01 0.01 0.01 0.02 0.01 0.01 0.01 0.01 
    ##  481  482  483  484  485  486  487  488  489  490  491  492  493  494  495  496 
    ## 0.02 0.02 0.02 0.02 0.01 0.01 0.01 0.01 0.02 0.02 0.03 0.02 0.02 0.01 0.01 0.01 
    ##  497  498  499  500  501  502  503  504  505  506 
    ## 0.01 0.00 0.00 0.01 0.00 0.02 0.02 0.02 0.02 0.02

``` r
which(Pii > 2*p_prime/n)
```

    ##   9  49 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 160 204 
    ##   9  49 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 160 204 
    ## 205 254 258 284 291 292 293 353 354 355 356 365 366 368 369 375 381 399 405 406 
    ## 205 254 258 284 291 292 293 353 354 355 356 365 366 368 369 375 381 399 405 406 
    ## 411 415 419 428 
    ## 411 415 419 428

``` r
which(Pii > 0.5)
```

    ## named integer(0)

``` r
# Influence 
influencePlot(fit1, id.method="identify", 
              main="Influence Plot", 
              sub="Circle size is proportial to Cook's Distance" )
```

    ## Warning in plot.window(...): "id.method" is not a graphical parameter

    ## Warning in plot.xy(xy, type, ...): "id.method" is not a graphical parameter

    ## Warning in axis(side = side, at = at, labels = labels, ...): "id.method" is not
    ## a graphical parameter
    
    ## Warning in axis(side = side, at = at, labels = labels, ...): "id.method" is not
    ## a graphical parameter

    ## Warning in box(...): "id.method" is not a graphical parameter

    ## Warning in title(...): "id.method" is not a graphical parameter

    ## Warning in plot.xy(xy.coords(x, y), type = type, ...): "id.method" is not a
    ## graphical parameter

![](Prediction-of-Housing-Values-in-Boston_files/figure-gfm/unnamed-chunk-8-1.png)<!-- -->

    ##        StudRes        Hat       CookD
    ## 366  3.1450944 0.08694217 0.102814880
    ## 369  5.9158132 0.05181403 0.198886214
    ## 373  5.8088811 0.01867939 0.066955368
    ## 381 -1.1362724 0.26795916 0.052480914
    ## 419 -0.2106307 0.16956532 0.001008482

``` r
DFFITS <- dffits(fit1)
which(DFFITS > 1)
```

    ## 369 
    ## 369

``` r
D <- cooks.distance(fit1)
which(D > qf(0.2, p_prime, n-p_prime))
```

    ## named integer(0)

``` r
DFBETAS <- dfbetas(fit1)
head(DFBETAS)
```

    ##    (Intercept)           X1          X2           X5           X6           X8
    ## 1 -0.065022461 -0.011756250  0.01295879 -0.013160927  0.037901509  0.008231731
    ## 2 -0.008641399 -0.008983324  0.03821073  0.006977200 -0.003136247 -0.018497054
    ## 3 -0.014814066  0.013641464 -0.04336663  0.003422294  0.030130058  0.023428847
    ## 4 -0.035550713  0.026467770 -0.06578803  0.028635528  0.029962760  0.062014137
    ## 5 -0.088601997  0.038701608 -0.11939448  0.043119815  0.094618019  0.116805742
    ## 6 -0.006775489  0.018401546 -0.04502506  0.016399119 -0.002973799  0.041862791
    ##            X10           X11           X13
    ## 1 -0.001658457  7.366617e-02  0.0657147071
    ## 2  0.013136373  1.013373e-02  0.0002459833
    ## 3 -0.012326968 -2.083215e-05 -0.0125169375
    ## 4 -0.027562939  2.044882e-02 -0.0308870444
    ## 5 -0.052249182  3.568085e-02 -0.0041986396
    ## 6 -0.020427517  9.109784e-03 -0.0250223870

``` r
which(DFBETAS > 1)
```

    ## integer(0)

``` r
# Matrix with Y, Yhat, P, e, t
s <- summary(fit1)$sigma
Y. <- lnY
Y.hat <- fitted(fit1)
P <- hatvalues(fit1)
e <- residuals(fit1)
t <- rstudent(fit1) 
DFFITS <- dffits(fit1)
D <- cooks.distance(fit1)
res <- cbind(Y., Y.hat, P, e, t, DFFITS, D)
colnames(res) <- c("Y.", "Y.hat", "P", "e", "t","DFFITS", "D")
res
```

    ##           Y.     Y.hat           P             e             t        DFFITS
    ## 1   3.178054 31.232878 0.008363167 -7.232878e+00 -1.472914e+00 -1.352653e-01
    ## 2   3.072693 25.226270 0.006729495 -3.626270e+00 -7.366458e-01 -6.063399e-02
    ## 3   3.546740 31.178140 0.010574364  3.521860e+00  7.168037e-01  7.410299e-02
    ## 4   3.508556 28.798981 0.014804664  4.601019e+00  9.388003e-01  1.150830e-01
    ## 5   3.589059 28.077475 0.015087159  8.122525e+00  1.660700e+00  2.055398e-01
    ## 6   3.356897 25.222732 0.011971498  3.477268e+00  7.082193e-01  7.795739e-02
    ## 7   3.131137 22.678973 0.012209515  2.210269e-01  4.499958e-02  5.002940e-03
    ## 8   3.299534 19.017100 0.020706944  8.082900e+00  1.657315e+00  2.409942e-01
    ## 9   2.803360 10.626979 0.045669941  5.873021e+00  1.218305e+00  2.665152e-01
    ## 10  2.939162 18.511743 0.021544973  3.882567e-01  7.942297e-02  1.178552e-02
    ## 11  2.708050 18.535185 0.027279879 -3.535185e+00 -7.256774e-01 -1.215265e-01
    ## 12  2.939162 21.205993 0.015925468 -2.305993e+00 -4.704742e-01 -5.985052e-02
    ## 13  3.077312 20.519940 0.013785995  1.180060e+00  2.404576e-01  2.842968e-02
    ## 14  3.015535 20.154580 0.012679340  2.454204e-01  4.997784e-02  5.663654e-03
    ## 15  2.901422 20.009464 0.010204214 -1.809464e+00 -3.680708e-01 -3.737217e-02
    ## 16  2.990720 19.880300 0.012711769  1.970013e-02  4.011826e-03  4.552219e-04
    ## 17  3.139833 21.305939 0.014473300  1.794061e+00  3.657264e-01  4.432063e-02
    ## 18  2.862201 17.421731 0.009264811  7.826898e-02  1.591131e-02  1.538670e-03
    ## 19  3.005683 17.582915 0.012459973  2.617085e+00  5.330399e-01  5.987436e-02
    ## 20  2.901422 18.922138 0.010595300 -7.221378e-01 -1.469053e-01 -1.520222e-02
    ## 21  2.610070 12.831523 0.012915472  7.684766e-01  1.565161e-01  1.790346e-02
    ## 22  2.975530 18.146089 0.008928375  1.453911e+00  2.955415e-01  2.805125e-02
    ## 23  2.721295 16.175937 0.012204472 -9.759371e-01 -1.987012e-01 -2.208648e-02
    ## 24  2.674149 14.034183 0.012167305  4.658167e-01  9.483578e-02  1.052514e-02
    ## 25  2.747271 16.039769 0.010003783 -4.397685e-01 -8.943465e-02 -8.990237e-03
    ## 26  2.631889 14.508253 0.010371445 -6.082532e-01 -1.237228e-01 -1.266582e-02
    ## 27  2.809403 15.999685 0.010087854  6.003151e-01  1.220906e-01  1.232490e-02
    ## 28  2.694627 15.900612 0.011082633 -1.100612e+00 -2.239604e-01 -2.370897e-02
    ## 29  2.912351 20.227069 0.011003524 -1.827069e+00 -3.718031e-01 -3.921764e-02
    ## 30  3.044522 21.714584 0.011606729 -7.145844e-01 -1.454430e-01 -1.576097e-02
    ## 31  2.541602 11.899979 0.015537243  8.000215e-01  1.631581e-01  2.049726e-02
    ## 32  2.674149 18.737211 0.009060508 -4.237211e+00 -8.619388e-01 -8.241934e-02
    ## 33  2.580217 10.371817 0.027799236  2.828183e+00  5.805932e-01  9.817715e-02
    ## 34  2.572612 14.871647 0.010577188 -1.771647e+00 -3.604441e-01 -3.726766e-02
    ## 35  2.602690 15.381382 0.013757146 -1.881382e+00 -3.833931e-01 -4.528105e-02
    ## 36  2.939162 23.584078 0.007543572 -4.684078e+00 -9.522697e-01 -8.302191e-02
    ## 37  2.995732 22.219871 0.007262590 -2.219871e+00 -4.509147e-01 -3.856763e-02
    ## 38  3.044522 22.894440 0.007674328 -1.894440e+00 -3.848695e-01 -3.384594e-02
    ## 39  3.206803 22.734523 0.006148722  1.965477e+00  3.989991e-01  3.138367e-02
    ## 40  3.427515 31.294786 0.029077112 -4.947860e-01 -1.016072e-01 -1.758360e-02
    ## 41  3.552487 34.342631 0.029357812  5.573689e-01  1.144758e-01  1.990885e-02
    ## 42  3.280911 28.166545 0.010630290 -1.566545e+00 -3.187153e-01 -3.303666e-02
    ## 43  3.230804 25.175714 0.010695526  1.242863e-01  2.528445e-02  2.628994e-03
    ## 44  3.206803 24.441050 0.009579978  2.589505e-01  5.265058e-02  5.178163e-03
    ## 45  3.054001 22.694002 0.009430824 -1.494002e+00 -3.037694e-01 -2.963988e-02
    ## 46  2.960105 21.669371 0.010239379 -2.369371e+00 -4.820195e-01 -4.902712e-02
    ## 47  2.995732 19.905826 0.009850168  9.417399e-02  1.915030e-02  1.910060e-03
    ## 48  2.809403 17.440128 0.016404212 -8.401278e-01 -1.714134e-01 -2.213676e-02
    ## 49  2.667228  7.930851 0.044535303  6.469149e+00  1.341595e+00  2.896451e-01
    ## 50  2.965273 16.544706 0.014571721  2.855294e+00  5.822126e-01  7.079857e-02
    ## 51  2.980619 20.440064 0.010931965 -7.400639e-01 -1.505778e-01 -1.583059e-02
    ## 52  3.020425 23.294536 0.009049803 -2.794536e+00 -5.682245e-01 -5.430172e-02
    ## 53  3.218876 27.211817 0.008931682 -2.211817e+00 -4.496565e-01 -4.268701e-02
    ## 54  3.152736 23.371689 0.009698161  2.831148e-02  5.756701e-03  5.696847e-04
    ## 55  2.939162 17.396416 0.033317683  1.503584e+00  3.094729e-01  5.745372e-02
    ## 56  3.566712 30.183511 0.032740321  5.216489e+00  1.074500e+00  1.976863e-01
    ## 57  3.206803 25.513435 0.026758533 -8.134348e-01 -1.668474e-01 -2.766562e-02
    ## 58  3.453157 32.151965 0.032524134 -5.519648e-01 -1.135512e-01 -2.081971e-02
    ## 59  3.148453 20.714502 0.015212647  2.585498e+00  5.273386e-01  6.554215e-02
    ## 60  2.975530 19.834736 0.010080924 -2.347361e-01 -4.773929e-02 -4.817550e-03
    ## 61  2.928524 16.454489 0.011904471  2.245511e+00  4.571957e-01  5.018313e-02
    ## 62  2.772589 17.260580 0.010386135 -1.260580e+00 -2.564255e-01 -2.626971e-02
    ## 63  3.100092 22.936493 0.011508317 -7.364931e-01 -1.498949e-01 -1.617359e-02
    ## 64  3.218876 21.521122 0.018296605  3.478878e+00  7.108289e-01  9.704209e-02
    ## 65  3.496508 23.188025 0.032984923  9.811975e+00  2.027340e+00  3.744276e-01
    ## 66  3.157000 30.594458 0.025057903 -7.094458e+00 -1.456975e+00 -2.335797e-01
    ## 67  2.965273 25.451264 0.028843274 -6.051264e+00 -1.244438e+00 -2.144623e-01
    ## 68  3.091042 21.747875 0.010742667  2.521252e-01  5.129295e-02  5.345141e-03
    ## 69  2.856470 17.814067 0.011906749 -4.140674e-01 -8.428885e-02 -9.252685e-03
    ## 70  3.039749 21.387753 0.010396251 -4.877530e-01 -9.921298e-02 -1.016895e-02
    ## 71  3.186353 25.702545 0.009223149 -1.502545e+00 -3.054748e-01 -2.947318e-02
    ## 72  3.077312 22.083248 0.009503911 -3.832480e-01 -7.792038e-02 -7.632659e-03
    ## 73  3.126761 24.932395 0.011313197 -2.132395e+00 -4.340259e-01 -4.642789e-02
    ## 74  3.152736 24.537130 0.009183174 -1.137130e+00 -2.311702e-01 -2.225520e-02
    ## 75  3.182212 26.590900 0.010831944 -2.490900e+00 -5.069074e-01 -5.304528e-02
    ## 76  3.063391 25.070005 0.009624317 -3.670005e+00 -7.466301e-01 -7.360215e-02
    ## 77  2.995732 24.030351 0.010218792 -4.030351e+00 -8.202808e-01 -8.334753e-02
    ## 78  3.034953 24.350885 0.010207433 -3.550885e+00 -7.225832e-01 -7.337938e-02
    ## 79  3.054001 22.204416 0.010287006 -1.004416e+00 -2.043018e-01 -2.082869e-02
    ## 80  3.010621 23.301645 0.011550932 -3.001645e+00 -6.111398e-01 -6.606508e-02
    ## 81  3.332205 28.616786 0.006054166 -6.167858e-01 -1.251857e-01 -9.770135e-03
    ## 82  3.173878 27.104998 0.005417001 -3.204998e+00 -6.505601e-01 -4.801162e-02
    ## 83  3.210844 26.090109 0.005994443 -1.290109e+00 -2.618527e-01 -2.033467e-02
    ## 84  3.131137 25.101168 0.006202288 -2.201168e+00 -4.468756e-01 -3.530316e-02
    ## 85  3.173878 24.816113 0.006620833 -9.161125e-01 -1.859950e-01 -1.518449e-02
    ## 86  3.280911 28.022162 0.007166695 -1.422162e+00 -2.888300e-01 -2.453938e-02
    ## 87  3.113515 22.017142 0.007549369  4.828577e-01  9.807624e-02  8.553910e-03
    ## 88  3.100092 25.912773 0.008512295 -3.712773e+00 -7.549166e-01 -6.994854e-02
    ## 89  3.161247 31.586368 0.007774404 -7.986368e+00 -1.626651e+00 -1.439868e-01
    ## 90  3.356897 31.780083 0.008047610 -3.080083e+00 -6.260131e-01 -5.638602e-02
    ## 91  3.117950 27.834467 0.006835667 -5.234467e+00 -1.064025e+00 -8.827379e-02
    ## 92  3.091042 28.124934 0.007068559 -6.124934e+00 -1.245704e+00 -1.051044e-01
    ## 93  3.131137 28.660991 0.008851595 -5.760991e+00 -1.172530e+00 -1.108065e-01
    ## 94  3.218876 28.801941 0.011256766 -3.801941e+00 -7.741422e-01 -8.260110e-02
    ## 95  3.025291 26.601063 0.009452147 -6.001063e+00 -1.221907e+00 -1.193619e-01
    ## 96  3.346389 29.809803 0.008776809 -1.409803e+00 -2.865521e-01 -2.696411e-02
    ## 97  3.063391 25.323396 0.009050211 -3.923396e+00 -7.980128e-01 -7.626292e-02
    ## 98  3.655840 37.053796 0.021178379  1.646204e+00  3.367258e-01  4.953031e-02
    ## 99  3.779634 36.396505 0.017114753  7.403495e+00  1.514545e+00  1.998555e-01
    ## 100 3.502550 33.295858 0.012680601 -9.585830e-02 -1.952073e-02 -2.212265e-03
    ## 101 3.314186 25.910130 0.009685204  1.589870e+00  3.233075e-01  3.197301e-02
    ## 102 3.277145 26.987695 0.010322658 -4.876954e-01 -9.919757e-02 -1.013095e-02
    ## 103 2.923162 24.012670 0.008689117 -5.412670e+00 -1.101367e+00 -1.031133e-01
    ## 104 2.960105 21.361638 0.008308910 -2.061638e+00 -4.189825e-01 -3.835127e-02
    ## 105 3.000720 22.543311 0.009574792 -2.443311e+00 -4.969022e-01 -4.885677e-02
    ## 106 2.970414 19.425431 0.012193781  7.456889e-02  1.518157e-02  1.686748e-03
    ## 107 2.970414 17.990771 0.012888321  1.509229e+00  3.074031e-01  3.512556e-02
    ## 108 3.015535 21.848928 0.011094779 -1.448928e+00 -2.948510e-01 -3.123090e-02
    ## 109 2.985682 23.812053 0.009809830 -4.012053e+00 -8.163828e-01 -8.125784e-02
    ## 110 2.965273 20.814344 0.009658762 -1.414344e+00 -2.876033e-01 -2.840286e-02
    ## 111 3.077312 21.756930 0.008096008 -5.693037e-02 -1.156656e-02 -1.044972e-03
    ## 112 3.126761 27.830633 0.006139563 -5.030633e+00 -1.022143e+00 -8.033740e-02
    ## 113 2.933857 21.683004 0.008357876 -2.883004e+00 -5.860207e-01 -5.380014e-02
    ## 114 2.928524 21.626835 0.007898956 -2.926835e+00 -5.947987e-01 -5.307340e-02
    ## 115 2.917771 26.412952 0.007502653 -7.912952e+00 -1.611397e+00 -1.401023e-01
    ## 116 2.906901 21.826559 0.007736492 -3.526559e+00 -7.167329e-01 -6.328720e-02
    ## 117 3.054001 24.508008 0.005830396 -3.308008e+00 -6.716278e-01 -5.143366e-02
    ## 118 2.954910 24.813966 0.007200480 -5.613966e+00 -1.141573e+00 -9.721955e-02
    ## 119 3.015535 21.796466 0.007825354 -1.396466e+00 -2.837046e-01 -2.519557e-02
    ## 120 2.960105 21.777267 0.007850783 -2.477267e+00 -5.033733e-01 -4.477733e-02
    ## 121 3.091042 21.201762 0.016049574  7.982378e-01  1.628367e-01  2.079684e-02
    ## 122 3.010621 21.893413 0.015852760 -1.593413e+00 -3.250421e-01 -4.125361e-02
    ## 123 3.020425 19.849861 0.017819343  6.501395e-01  1.327436e-01  1.787984e-02
    ## 124 2.850707 15.478344 0.028773263  1.821656e+00  3.740781e-01  6.438675e-02
    ## 125 2.933857 19.829201 0.017969243 -1.029201e+00 -2.101610e-01 -2.842853e-02
    ## 126 3.063391 21.816901 0.016799389 -4.169007e-01 -8.507650e-02 -1.112078e-02
    ## 127 2.753661 13.719890 0.032603297  1.980110e+00  4.074316e-01  7.479682e-02
    ## 128 2.785011 16.848398 0.011311781 -6.483976e-01 -1.319515e-01 -1.411400e-02
    ## 129 2.890372 20.815957 0.011499916 -2.815957e+00 -5.732927e-01 -6.183514e-02
    ## 130 2.660260 15.645259 0.010617948 -1.345259e+00 -2.736853e-01 -2.835239e-02
    ## 131 2.954910 22.017342 0.010815519 -2.817342e+00 -5.733763e-01 -5.995491e-02
    ## 132 2.975530 21.370264 0.010026726 -1.770264e+00 -3.600626e-01 -3.623647e-02
    ## 133 3.135494 22.156122 0.010760302  8.438785e-01  1.716868e-01  1.790599e-02
    ## 134 2.912351 17.552216 0.009337031  8.477843e-01  1.723575e-01  1.673292e-02
    ## 135 2.747271 16.153214 0.009203925 -5.532142e-01 -1.124609e-01 -1.083917e-02
    ## 136 2.895912 19.089917 0.010727280 -9.899166e-01 -2.013971e-01 -2.097201e-02
    ## 137 2.856470 17.753737 0.010162325 -3.537371e-01 -7.194421e-02 -7.289713e-03
    ## 138 2.839078 21.295933 0.011342346 -4.195933e+00 -8.545156e-01 -9.152684e-02
    ## 139 2.587764 15.404593 0.013437415 -2.104593e+00 -4.288261e-01 -5.004685e-02
    ## 140 2.879198 18.166424 0.011946074 -3.664243e-01 -7.459184e-02 -8.201884e-03
    ## 141 2.639057 15.202712 0.019096736 -1.202712e+00 -2.457366e-01 -3.428754e-02
    ## 142 2.667228  4.950546 0.035685951  9.449454e+00  1.954603e+00  3.760088e-01
    ## 143 2.595255 12.460039 0.040514838  9.399606e-01  1.941789e-01  3.990156e-02
    ## 144 2.747271 12.748883 0.040087381  2.851117e+00  5.890415e-01  1.203743e-01
    ## 145 2.468100  9.058332 0.045925172  2.741668e+00  5.681458e-01  1.246505e-01
    ## 146 2.624669 14.813880 0.044647012 -1.013880e+00 -2.099031e-01 -4.537672e-02
    ## 147 2.747271 18.826803 0.038458470 -3.226803e+00 -6.661585e-01 -1.332262e-01
    ## 148 2.681022  8.881682 0.046470170  5.718318e+00  1.186620e+00  2.619580e-01
    ## 149 2.879198 10.514265 0.043830085  7.285735e+00  1.511117e+00  3.235316e-01
    ## 150 2.734368 15.975570 0.037313373 -5.755699e-01 -1.187016e-01 -2.336934e-02
    ## 151 3.068053 22.146808 0.037936714 -6.468078e-01 -1.334370e-01 -2.649746e-02
    ## 152 2.975530 19.725711 0.045031165 -1.257110e-01 -2.602998e-02 -5.652437e-03
    ## 153 2.727853 18.773221 0.053998510 -3.473221e+00 -7.229531e-01 -1.727250e-01
    ## 154 2.965273 19.476134 0.038825336 -7.613429e-02 -1.571355e-02 -3.158135e-03
    ## 155 2.833213 21.433630 0.037783897 -4.433630e+00 -9.153444e-01 -1.813851e-01
    ## 156 2.747271 21.414134 0.037745162 -5.814134e+00 -1.201062e+00 -2.378763e-01
    ## 157 2.572612 17.306357 0.043426356 -4.206357e+00 -8.709108e-01 -1.855629e-01
    ## 158 3.720862 34.741598 0.016839383  6.558402e+00  1.340807e+00  1.754758e-01
    ## 159 3.190476 30.312285 0.020805299 -6.012285e+00 -1.231297e+00 -1.794796e-01
    ## 160 3.148453 27.251662 0.045651161 -3.951662e+00 -8.190580e-01 -1.791377e-01
    ## 161 3.295837 31.523367 0.019953137 -4.523367e+00 -9.253538e-01 -1.320353e-01
    ## 162 3.912023 38.396575 0.020500661  1.160343e+01  2.385927e+00  3.451747e-01
    ## 163 3.912023 39.433383 0.022203848  1.056662e+01  2.172517e+00  3.273808e-01
    ## 164 3.912023 40.838955 0.029166725  9.161045e+00  1.888090e+00  3.272610e-01
    ## 165 3.122365 25.492441 0.015893867 -2.792441e+00 -5.697707e-01 -7.240923e-02
    ## 166 3.218876 27.665730 0.015172919 -2.665730e+00 -5.437013e-01 -6.748620e-02
    ## 167 3.912023 38.941390 0.022439056  1.105861e+01  2.274980e+00  3.446736e-01
    ## 168 3.169686 25.339382 0.015429927 -1.539382e+00 -3.139505e-01 -3.930247e-02
    ## 169 3.169686 28.163572 0.013490412 -4.363572e+00 -8.896777e-01 -1.040386e-01
    ## 170 3.104587 28.125741 0.012841135 -5.825741e+00 -1.188146e+00 -1.355120e-01
    ## 171 2.856470 24.109278 0.014974161 -6.709278e+00 -1.370464e+00 -1.689721e-01
    ## 172 2.949688 25.425783 0.015482160 -6.325783e+00 -1.292192e+00 -1.620433e-01
    ## 173 3.139833 22.540546 0.013619848  5.594536e-01  1.139836e-01  1.339388e-02
    ## 174 3.161247 29.047511 0.008576416 -5.447511e+00 -1.108410e+00 -1.030917e-01
    ## 175 3.117950 26.360419 0.011706282 -3.760419e+00 -7.658518e-01 -8.335107e-02
    ## 176 3.380995 30.914729 0.008814794 -1.514729e+00 -3.078888e-01 -2.903505e-02
    ## 177 3.144152 25.487055 0.007779293 -2.287055e+00 -4.646885e-01 -4.114602e-02
    ## 178 3.202746 29.164980 0.008695214 -4.564980e+00 -9.285544e-01 -8.696488e-02
    ## 179 3.397858 31.636398 0.008118076 -1.736398e+00 -3.528325e-01 -3.192017e-02
    ## 180 3.616309 32.697753 0.011764586  4.502247e+00  9.171957e-01  1.000737e-01
    ## 181 3.683867 34.631696 0.019575772  5.168304e+00  1.057365e+00  1.494092e-01
    ## 182 3.589059 27.183923 0.012030800  9.016077e+00  1.841708e+00  2.032340e-01
    ## 183 3.634951 33.722137 0.013022262  4.177863e+00  8.515549e-01  9.781427e-02
    ## 184 3.481240 30.611426 0.011278335  1.888574e+00  3.843764e-01  4.105274e-02
    ## 185 3.273364 21.885552 0.013328433  4.514448e+00  9.204153e-01  1.069762e-01
    ## 186 3.387774 24.152701 0.009350985  5.447299e+00  1.108802e+00  1.077265e-01
    ## 187 3.912023 35.945064 0.018254500  1.405494e+01  2.894419e+00  3.946816e-01
    ## 188 3.465736 34.334586 0.020228212 -2.334586e+00 -4.773555e-01 -6.858960e-02
    ## 189 3.394508 33.426425 0.017859287 -3.626425e+00 -7.408443e-01 -9.990153e-02
    ## 190 3.552487 35.534930 0.016131357 -6.349302e-01 -1.295268e-01 -1.658542e-02
    ## 191 3.610918 31.891518 0.013696859  5.108482e+00  1.041973e+00  1.227896e-01
    ## 192 3.417727 31.256084 0.013901722 -7.560843e-01 -1.540691e-01 -1.829320e-02
    ## 193 3.594569 34.055211 0.014635652  2.344789e+00  4.780796e-01  5.826501e-02
    ## 194 3.437208 32.681303 0.012452168 -1.581303e+00 -3.220151e-01 -3.615927e-02
    ## 195 3.370738 32.243150 0.013302940 -3.143150e+00 -6.405421e-01 -7.437544e-02
    ## 196 3.912023 40.605677 0.028143022  9.394323e+00  1.935500e+00  3.293649e-01
    ## 197 3.505557 36.915398 0.029365005 -3.615398e+00 -7.429585e-01 -1.292265e-01
    ## 198 3.411148 33.666907 0.031829356 -3.366907e+00 -6.927236e-01 -1.256024e-01
    ## 199 3.543854 35.453095 0.030676880 -8.530949e-01 -1.753361e-01 -3.119196e-02
    ## 200 3.552487 31.596131 0.031106275  3.303869e+00  6.794878e-01  1.217496e-01
    ## 201 3.493473 32.310923 0.031315622  5.890774e-01  1.211107e-01  2.177569e-02
    ## 202 3.182212 30.090137 0.030028075 -5.990137e+00 -1.232583e+00 -2.168704e-01
    ## 203 3.744787 38.394625 0.026491425  3.905375e+00  8.014359e-01  1.322061e-01
    ## 204 3.881564 41.320993 0.044039340  7.179007e+00  1.489045e+00  3.196010e-01
    ## 205 3.912023 42.576575 0.045177900  7.423425e+00  1.540902e+00  3.351790e-01
    ## 206 3.117950 22.563149 0.006098918  3.685103e-02  7.479508e-03  5.859058e-04
    ## 207 3.194583 23.664399 0.004864271  7.356007e-01  1.492126e-01  1.043214e-02
    ## 208 3.113515 17.513402 0.008837654  4.986598e+00  1.014558e+00  9.580169e-02
    ## 209 3.194583 20.728148 0.005986699  3.671852e+00  7.456367e-01  5.786619e-02
    ## 210 2.995732 13.631186 0.016397477  6.368814e+00  1.301620e+00  1.680594e-01
    ## 211 3.077312 19.391745 0.008139934  2.308255e+00  4.690831e-01  4.249472e-02
    ## 212 2.960105 13.699746 0.018089114  5.600254e+00  1.145091e+00  1.554220e-01
    ## 213 3.109061 19.786612 0.007635015  2.613388e+00  5.309901e-01  4.657530e-02
    ## 214 3.335770 25.363810 0.004944036  2.736190e+00  5.552036e-01  3.913536e-02
    ## 215 3.165475 10.764040 0.031354919  1.293596e+01  2.678738e+00  4.819486e-01
    ## 216 3.218876 24.521910 0.005257036  4.780896e-01  9.699578e-02  7.051279e-03
    ## 217 3.148453 23.266086 0.008020130  3.391350e-02  6.889951e-03  6.195201e-04
    ## 218 3.356897 27.999097 0.006303007  7.009034e-01  1.422771e-01  1.133136e-02
    ## 219 3.068053 21.402365 0.010415090  9.763484e-02  1.985973e-02  2.037410e-03
    ## 220 3.135494 26.534851 0.006167309 -3.534851e+00 -7.178520e-01 -5.654916e-02
    ## 221 3.284664 29.855651 0.007589492 -3.155651e+00 -6.412363e-01 -5.607623e-02
    ## 222 3.077312 19.843797 0.015649966  1.856203e+00  3.786242e-01  4.774087e-02
    ## 223 3.314186 28.806802 0.006431558 -1.306802e+00 -2.652997e-01 -2.134499e-02
    ## 224 3.404525 29.035889 0.005851965  1.064111e+00  2.159617e-01  1.656922e-02
    ## 225 3.802208 38.313776 0.022657508  6.486224e+00  1.329953e+00  2.024972e-01
    ## 226 3.912023 39.896658 0.033512560  1.010334e+01  2.088639e+00  3.889279e-01
    ## 227 3.627004 37.468378 0.018169864  1.316225e-01  2.687863e-02  3.656493e-03
    ## 228 3.453157 32.096341 0.008098774 -4.963408e-01 -1.008429e-01 -9.112144e-03
    ## 229 3.843744 35.355578 0.013084932  1.134442e+01  2.323205e+00  2.675059e-01
    ## 230 3.449988 30.807090 0.008930912  6.929097e-01  1.408407e-01  1.336978e-02
    ## 231 3.190476 23.650504 0.005992591  6.494963e-01  1.318209e-01  1.023521e-02
    ## 232 3.456317 33.044919 0.009919624 -1.344919e+00 -2.735197e-01 -2.737796e-02
    ## 233 3.730501 38.054006 0.023807695  3.645994e+00  7.471148e-01  1.166751e-01
    ## 234 3.877432 37.163474 0.022063333  1.113653e+01  2.290733e+00  3.440763e-01
    ## 235 3.367296 28.674767 0.005392378  3.252332e-01  6.598812e-02  4.858811e-03
    ## 236 3.178054 24.503549 0.005511956 -5.035488e-01 -1.021742e-01 -7.606665e-03
    ## 237 3.222868 26.715598 0.005178704 -1.615598e+00 -3.277952e-01 -2.365052e-02
    ## 238 3.449988 32.350794 0.009905596 -8.507943e-01 -1.730192e-01 -1.730598e-02
    ## 239 3.165475 28.094952 0.006379370 -4.394952e+00 -8.928684e-01 -7.154282e-02
    ## 240 3.148453 28.043521 0.006103126 -4.743521e+00 -9.636764e-01 -7.551561e-02
    ## 241 3.091042 26.785823 0.009790158 -4.785823e+00 -9.740985e-01 -9.685769e-02
    ## 242 3.000720 22.949138 0.008522846 -2.849138e+00 -5.791804e-01 -5.369883e-02
    ## 243 3.100092 23.635284 0.009651633 -1.435284e+00 -2.918610e-01 -2.881260e-02
    ## 244 3.165475 27.122135 0.009313407 -3.422135e+00 -6.960428e-01 -6.748731e-02
    ## 245 2.867899 15.836903 0.015709546  1.763097e+00  3.596384e-01  4.543455e-02
    ## 246 2.917771 12.579787 0.019923619  5.920213e+00  1.211837e+00  1.727820e-01
    ## 247 3.190476 19.630095 0.014656072  4.669905e+00  9.528095e-01  1.162040e-01
    ## 248 3.020425 19.573833 0.014736958  9.261668e-01  1.888094e-01  2.309146e-02
    ## 249 3.198673 21.111470 0.013388765  3.388530e+00  6.906244e-01  8.045242e-02
    ## 250 3.265759 23.914324 0.014315594  2.285676e+00  4.659460e-01  5.615279e-02
    ## 251 3.194583 23.982625 0.011011928  4.173754e-01  8.492380e-02  8.961187e-03
    ## 252 3.210844 25.058533 0.012615437 -2.585325e-01 -5.264634e-02 -5.950811e-03
    ## 253 3.387774 24.970683 0.026199275  4.629317e+00  9.501050e-01  1.558408e-01
    ## 254 3.756538 30.252237 0.047245781  1.254776e+01  2.619108e+00  5.832362e-01
    ## 255 3.086487 24.765988 0.024919789 -2.865988e+00 -5.874895e-01 -9.391871e-02
    ## 256 3.039749 22.333568 0.026538858 -1.433568e+00 -2.940301e-01 -4.854825e-02
    ## 257 3.784190 37.355462 0.030479586  6.644538e+00  1.368041e+00  2.425633e-01
    ## 258 3.912023 43.548003 0.040712584  6.451997e+00  1.335346e+00  2.750958e-01
    ## 259 3.583519 36.330555 0.022432996 -3.305553e-01 -6.764999e-02 -1.024798e-02
    ## 260 3.404525 34.649345 0.021624179 -4.549345e+00 -9.314734e-01 -1.384801e-01
    ## 261 3.520461 34.487679 0.021305131 -6.876795e-01 -1.406585e-01 -2.075317e-02
    ## 262 3.763523 37.032869 0.023040137  6.067131e+00  1.243989e+00  1.910383e-01
    ## 263 3.887730 41.142942 0.034264817  7.657058e+00  1.580588e+00  2.977241e-01
    ## 264 3.433987 34.098429 0.022938717 -3.098429e+00 -6.345295e-01 -9.722444e-02
    ## 265 3.597312 35.596980 0.021716743  9.030200e-01  1.847459e-01  2.752580e-02
    ## 266 3.126761 27.477680 0.031158830 -4.677680e+00 -9.625079e-01 -1.726110e-01
    ## 267 3.424263 30.780031 0.023370136 -8.003118e-02 -1.638662e-02 -2.534865e-03
    ## 268 3.912023 40.848083 0.030925146  9.151917e+00  1.887918e+00  3.372565e-01
    ## 269 3.772761 39.182177 0.019613479  4.317823e+00  8.830845e-01  1.249053e-01
    ## 270 3.030134 22.466676 0.009831511 -1.766676e+00 -3.592971e-01 -3.580217e-02
    ## 271 3.049273 21.787346 0.008267172 -6.873460e-01 -1.396631e-01 -1.275154e-02
    ## 272 3.226844 26.921907 0.007835839 -1.721907e+00 -3.498375e-01 -3.108976e-02
    ## 273 3.194583 28.270535 0.007924455 -3.870535e+00 -7.868001e-01 -7.031965e-02
    ## 274 3.561046 32.934081 0.014793690  2.265919e+00  4.620289e-01  5.661661e-02
    ## 275 3.478158 33.216449 0.012601467 -8.164495e-01 -1.662609e-01 -1.878254e-02
    ## 276 3.465736 33.627432 0.011761590 -1.627432e+00 -3.312950e-01 -3.614240e-02
    ## 277 3.502550 32.833397 0.009677576  3.666031e-01  7.454270e-02  7.368857e-03
    ## 278 3.499533 31.974372 0.008528667  1.125628e+00  2.287561e-01  2.121647e-02
    ## 279 3.370738 29.964394 0.011196990 -8.643941e-01 -1.758998e-01 -1.871807e-02
    ## 280 3.558201 34.285476 0.011415105  8.145239e-01  1.657692e-01  1.781299e-02
    ## 281 3.815512 38.131535 0.015581968  7.268465e+00  1.485634e+00  1.869103e-01
    ## 282 3.566712 33.376494 0.009951046  2.023506e+00  4.115714e-01  4.126209e-02
    ## 283 3.828641 37.061515 0.013761732  8.938485e+00  1.827363e+00  2.158592e-01
    ## 284 3.912023 41.847737 0.036303231  8.152263e+00  1.685166e+00  3.270732e-01
    ## 285 3.471966 32.177027 0.027194396  2.297275e-02  4.712973e-03  7.879916e-04
    ## 286 3.091042 28.090006 0.013741658 -6.090006e+00 -1.242775e+00 -1.466954e-01
    ## 287 3.000720 20.538468 0.028530149 -4.384679e-01 -9.001638e-02 -1.542620e-02
    ## 288 3.144152 26.189951 0.010752152 -2.989951e+00 -6.085110e-01 -6.344006e-02
    ## 289 3.104587 26.366461 0.010168229 -4.066461e+00 -8.276191e-01 -8.388271e-02
    ## 290 3.210844 26.326540 0.010311162 -1.526540e+00 -3.105247e-01 -3.169572e-02
    ## 291 3.349904 33.055657 0.039856046 -4.555657e+00 -9.415981e-01 -1.918424e-01
    ## 292 3.618993 34.095058 0.039600377  3.204942e+00  6.620349e-01  1.344326e-01
    ## 293 3.328627 31.353112 0.039848152 -3.453112e+00 -7.134415e-01 -1.453425e-01
    ## 294 3.173878 25.585988 0.015047810 -1.685988e+00 -3.437903e-01 -4.249352e-02
    ## 295 3.077312 24.094794 0.015521417 -2.394794e+00 -4.884998e-01 -6.133763e-02
    ## 296 3.353407 28.429777 0.016145870  1.702234e-01  3.472557e-02  4.448512e-03
    ## 297 3.299534 27.288322 0.015915165 -1.883221e-01 -3.841321e-02 -4.885060e-03
    ## 298 3.010621 18.960678 0.022413651  1.339322e+00  2.741166e-01  4.150630e-02
    ## 299 3.113515 29.508174 0.021656800 -7.008174e+00 -1.436666e+00 -2.137506e-01
    ## 300 3.367296 32.475451 0.019585164 -3.475451e+00 -7.105950e-01 -1.004340e-01
    ## 301 3.210844 31.044950 0.019641991 -6.244950e+00 -1.278338e+00 -1.809448e-01
    ## 302 3.091042 28.336829 0.007654677 -6.336829e+00 -1.289324e+00 -1.132385e-01
    ## 303 3.273364 28.405197 0.007508661 -2.005197e+00 -4.073438e-01 -3.543064e-02
    ## 304 3.499533 32.505224 0.007582386  5.947756e-01  1.208112e-01  1.055998e-02
    ## 305 3.586293 31.995500 0.012809013  4.104500e+00  8.364898e-01  9.528354e-02
    ## 306 3.346389 29.327864 0.014064116 -9.278637e-01 -1.890908e-01 -2.258407e-02
    ## 307 3.508556 34.374024 0.018900187 -9.740239e-01 -1.989873e-01 -2.761860e-02
    ## 308 3.339322 31.334529 0.015517208 -3.134529e+00 -6.395023e-01 -8.028693e-02
    ## 309 3.126761 29.274188 0.007870141 -6.474188e+00 -1.317512e+00 -1.173442e-01
    ## 310 3.010621 23.888747 0.005952751 -3.588747e+00 -7.287300e-01 -5.639258e-02
    ## 311 2.778819 19.012590 0.018461672 -2.912590e+00 -5.950803e-01 -8.161265e-02
    ## 312 3.095578 27.366761 0.010176790 -5.266761e+00 -1.072414e+00 -1.087400e-01
    ## 313 2.965273 23.532788 0.005479694 -4.132788e+00 -8.391494e-01 -6.228889e-02
    ## 314 3.072693 26.004449 0.005669589 -4.404449e+00 -8.944811e-01 -6.754320e-02
    ## 315 3.169686 25.952558 0.004441382 -2.152558e+00 -4.366161e-01 -2.916254e-02
    ## 316 2.785011 20.703769 0.006200442 -4.503769e+00 -9.149299e-01 -7.226862e-02
    ## 317 2.879198 17.681048 0.007039019  1.189522e-01  2.415469e-02  2.033721e-03
    ## 318 2.985682 18.425591 0.005541632  1.374409e+00  2.789020e-01  2.081983e-02
    ## 319 3.139833 24.699915 0.004007682 -1.599915e+00 -3.244217e-01 -2.057920e-02
    ## 320 3.044522 21.582399 0.004132801 -5.823993e-01 -1.180922e-01 -7.607512e-03
    ## 321 3.169686 24.946151 0.006783178 -1.146151e+00 -2.327225e-01 -1.923238e-02
    ## 322 3.139833 24.924176 0.007037005 -1.824176e+00 -3.704719e-01 -3.118765e-02
    ## 323 3.015535 22.814088 0.007664024 -2.414088e+00 -4.904830e-01 -4.310454e-02
    ## 324 2.917771 19.219508 0.007189357 -7.195075e-01 -1.461189e-01 -1.243421e-02
    ## 325 3.218876 25.217179 0.007812667 -2.171791e-01 -4.411812e-02 -3.914892e-03
    ## 326 3.202746 24.837024 0.010479393 -2.370238e-01 -4.821425e-02 -4.961707e-03
    ## 327 3.135494 23.748693 0.009694790 -7.486930e-01 -1.522384e-01 -1.506291e-02
    ## 328 3.100092 19.135151 0.007796540  3.064849e+00  6.228356e-01  5.521079e-02
    ## 329 2.960105 22.905870 0.017144293 -3.605870e+00 -7.363721e-01 -9.725507e-02
    ## 330 3.117950 26.261882 0.015814874 -3.661882e+00 -7.473176e-01 -9.473265e-02
    ## 331 2.985682 23.540180 0.018237733 -3.740180e+00 -7.642576e-01 -1.041650e-01
    ## 332 2.839078 20.677844 0.010024075 -3.577844e+00 -7.280077e-01 -7.325644e-02
    ## 333 2.965273 24.557360 0.008012732 -5.157360e+00 -1.048940e+00 -9.427309e-02
    ## 334 3.100092 21.667859 0.021396962  5.321410e-01  1.088488e-01  1.609520e-02
    ## 335 3.030134 21.050737 0.020503927 -3.507367e-01 -7.170955e-02 -1.037515e-02
    ## 336 3.049273 19.942447 0.016842782  1.157553e+00  2.362375e-01  3.092034e-02
    ## 337 2.970414 19.387620 0.012998248  1.123801e-01  2.288893e-02  2.626691e-03
    ## 338 2.917771 18.500488 0.013953906 -4.881428e-04 -9.947024e-05 -1.183293e-05
    ## 339 3.025291 21.502439 0.012068264 -9.024391e-01 -1.837233e-01 -2.030594e-02
    ## 340 2.944439 20.516256 0.011552745 -1.516256e+00 -3.086259e-01 -3.336555e-02
    ## 341 2.928524 20.696087 0.011874285 -1.996087e+00 -4.063877e-01 -4.454903e-02
    ## 342 3.487375 31.375035 0.012184773  1.324965e+00  2.697698e-01  2.996154e-02
    ## 343 2.803360 24.753968 0.022658984 -8.253968e+00 -1.694290e+00 -2.579793e-01
    ## 344 3.173878 28.396253 0.010053919 -4.496253e+00 -9.151795e-01 -9.222915e-02
    ## 345 3.440418 29.455851 0.011260096  1.744149e+00  3.549707e-01  3.788109e-02
    ## 346 2.862201 17.726073 0.024905177 -2.260732e-01 -4.632565e-02 -7.403600e-03
    ## 347 2.844909 16.062901 0.025412444  1.137099e+00  2.330809e-01  3.763739e-02
    ## 348 3.139833 25.834447 0.026355969 -2.734447e+00 -5.609215e-01 -9.228720e-02
    ## 349 3.198673 27.353678 0.022321010 -2.853678e+00 -5.841859e-01 -8.826933e-02
    ## 350 3.280911 24.013298 0.021299721  2.586702e+00  5.292235e-01  7.807306e-02
    ## 351 3.131137 22.129210 0.019167690  7.707895e-01  1.574868e-01  2.201566e-02
    ## 352 3.182212 22.183577 0.035267058  1.916423e+00  3.948671e-01  7.549741e-02
    ## 353 2.923162 18.073036 0.035896448  5.269641e-01  1.085974e-01  2.095478e-02
    ## 354 3.404525 23.828150 0.054653921  6.271850e+00  1.307502e+00  3.143819e-01
    ## 355 2.901422 14.848424 0.054023932  3.351576e+00  6.976166e-01  1.667131e-01
    ## 356 3.025291 17.332908 0.054091365  3.267092e+00  6.800393e-01  1.626198e-01
    ## 357 2.879198 15.824552 0.013061358  1.975448e+00  4.024263e-01  4.629515e-02
    ## 358 3.077312 18.825891 0.018676324  2.874109e+00  5.872769e-01  8.101818e-02
    ## 359 3.122365 18.290807 0.020876581  4.409193e+00  9.023843e-01  1.317657e-01
    ## 360 3.117950 17.964823 0.018895325  4.635177e+00  9.477558e-01  1.315273e-01
    ## 361 3.218876 21.802703 0.025740839  3.197297e+00  6.557356e-01  1.065867e-01
    ## 362 2.990720 18.041391 0.016939979  1.858609e+00  3.793638e-01  4.979919e-02
    ## 363 3.034953 16.933780 0.028554619  3.866220e+00  7.942337e-01  1.361687e-01
    ## 364 2.821379 16.514647 0.016241880  2.853531e-01  5.821500e-02  7.480125e-03
    ## 365 3.086487 34.751881 0.051863466 -1.285188e+01 -2.690119e+00 -6.291683e-01
    ## 366 3.314186 12.793815 0.086942174  1.470618e+01  3.145094e+00  9.705095e-01
    ## 367 3.086487 14.558147 0.022770945  7.341853e+00  1.506237e+00  2.299248e-01
    ## 368 3.139833 11.407072 0.054043871  1.169293e+01  2.447311e+00  5.849609e-01
    ## 369 3.912023 22.485529 0.051814030  2.751447e+01  5.915813e+00  1.382902e+00
    ## 370 3.912023 29.112275 0.023099665  2.088773e+01  4.357304e+00  6.700320e-01
    ## 371 3.912023 31.056118 0.024526763  1.894388e+01  3.941422e+00  6.249790e-01
    ## 372 3.912023 23.975106 0.015351601  2.602489e+01  5.464332e+00  6.822968e-01
    ## 373 3.912023 22.482358 0.018679394  2.751764e+01  5.808881e+00  8.014352e-01
    ## 374 2.624669  3.862961 0.026899124  9.937039e+00  2.046914e+00  3.403218e-01
    ## 375 2.624669 -1.598276 0.037503000  1.539828e+01  3.208696e+00  6.333765e-01
    ## 376 2.708050 24.556973 0.019221560 -9.556973e+00 -1.960223e+00 -2.744192e-01
    ## 377 2.631889 16.723563 0.014797641 -2.823563e+00 -5.758041e-01 -7.056808e-02
    ## 378 2.587764 18.855143 0.014392262 -5.555143e+00 -1.133705e+00 -1.369975e-01
    ## 379 2.572612 14.627075 0.016728072 -1.527075e+00 -3.116456e-01 -4.064874e-02
    ## 380 2.322388 15.522495 0.010248278 -5.322495e+00 -1.083829e+00 -1.102867e-01
    ## 381 2.341806 15.198336 0.267959161 -4.798336e+00 -1.136272e+00 -6.874626e-01
    ## 382 2.388763 17.190102 0.011269310 -6.290102e+00 -1.282130e+00 -1.368805e-01
    ## 383 2.424803 11.664566 0.008911137 -3.645658e-01 -7.409977e-02 -7.026307e-03
    ## 384 2.509599 11.235367 0.010020399  1.064633e+00  2.165221e-01  2.178370e-02
    ## 385 2.174752  2.312155 0.023037666  6.487845e+00  1.330547e+00  2.043198e-01
    ## 386 1.974081  6.209369 0.016267452  9.906313e-01  2.021093e-01  2.599008e-02
    ## 387 2.351375  4.378646 0.021637629  6.121354e+00  1.254239e+00  1.865242e-01
    ## 388 2.001480  3.811018 0.020765138  3.588982e+00  7.342748e-01  1.069258e-01
    ## 389 2.322388  4.656116 0.016617063  5.543884e+00  1.132684e+00  1.472396e-01
    ## 390 2.442347 12.460301 0.009069897 -9.603008e-01 -1.952079e-01 -1.867571e-02
    ## 391 2.714695 15.655587 0.008727292 -5.555870e-01 -1.129161e-01 -1.059496e-02
    ## 392 3.144152 15.896658 0.008751297  7.303342e+00  1.487620e+00  1.397774e-01
    ## 393 2.272126  7.991710 0.011516758  1.708290e+00  3.477160e-01  3.753230e-02
    ## 394 2.624669 18.866650 0.008127153 -5.066650e+00 -1.030510e+00 -9.328106e-02
    ## 395 2.541602 16.589135 0.008100588 -3.889135e+00 -7.906561e-01 -7.145162e-02
    ## 396 2.572612 19.010128 0.008578434 -5.910128e+00 -1.202805e+00 -1.118845e-01
    ## 397 2.525729 17.799369 0.009977668 -5.299369e+00 -1.078961e+00 -1.083173e-01
    ## 398 2.140066 14.726730 0.007833931 -6.226730e+00 -1.266964e+00 -1.125802e-01
    ## 399 1.609438  5.295293 0.040156338 -2.952934e-01 -6.098880e-02 -1.247461e-02
    ## 400 1.840550  9.591464 0.017976323 -3.291464e+00 -6.723895e-01 -9.097255e-02
    ## 401 1.722767 10.540737 0.017941235 -4.940737e+00 -1.009866e+00 -1.364965e-01
    ## 402 1.974081 16.483748 0.008690463 -9.283748e+00 -1.893554e+00 -1.772942e-01
    ## 403 2.493205 17.023446 0.009184923 -4.923446e+00 -1.001859e+00 -9.646021e-02
    ## 404 2.116256 11.673127 0.016879154 -3.373127e+00 -6.887026e-01 -9.024093e-02
    ## 405 2.140066  6.957710 0.044696734  1.542290e+00  3.193265e-01  6.907202e-02
    ## 406 1.609438  8.117872 0.139276594 -3.117872e+00 -6.803369e-01 -2.736726e-01
    ## 407 2.476538  6.422441 0.031368033  5.477559e+00  1.127609e+00  2.029190e-01
    ## 408 3.328627 19.200982 0.015560720  8.699018e+00  1.779725e+00  2.237553e-01
    ## 409 2.844909 12.447731 0.019457669  4.752269e+00  9.720218e-01  1.369267e-01
    ## 410 3.314186 20.563527 0.017269829  6.936473e+00  1.418717e+00  1.880714e-01
    ## 411 2.708050 18.520475 0.093344237 -3.520475e+00 -7.485488e-01 -2.401832e-01
    ## 412 2.844909 18.908637 0.016512176 -1.708637e+00 -3.486691e-01 -4.517842e-02
    ## 413 2.884801  2.904308 0.033679508  1.499569e+01  3.116827e+00  5.818821e-01
    ## 414 2.791165 12.120299 0.027785650  4.179701e+00  8.583838e-01  1.451145e-01
    ## 415 1.945910 -2.920065 0.067524020  9.920065e+00  2.087808e+00  5.618248e-01
    ## 416 1.974081 11.532955 0.022639139 -4.332955e+00 -8.875570e-01 -1.350824e-01
    ## 417 2.014903 15.380898 0.021194129 -7.880898e+00 -1.616080e+00 -2.378057e-01
    ## 418 2.341806  7.893274 0.017961514  2.506726e+00  5.119791e-01  6.924039e-02
    ## 419 2.174752  9.748550 0.169565321 -9.485496e-01 -2.106307e-01 -9.517819e-02
    ## 420 2.128232 16.568868 0.016819216 -8.168868e+00 -1.671707e+00 -2.186484e-01
    ## 421 2.815409 19.131225 0.009572913 -2.431225e+00 -4.944426e-01 -4.861011e-02
    ## 422 2.653242 17.413162 0.009329570 -3.213162e+00 -6.535063e-01 -6.341850e-02
    ## 423 3.034953 18.001769 0.012046590  2.798231e+00  5.698393e-01  6.292399e-02
    ## 424 2.595255 15.064275 0.013535058 -1.664275e+00 -3.391013e-01 -3.972086e-02
    ## 425 2.459589 16.553114 0.012677692 -4.853114e+00 -9.892679e-01 -1.120997e-01
    ## 426 2.116256 11.995954 0.009646673 -3.695954e+00 -7.519237e-01 -7.421087e-02
    ## 427 2.322388 18.292025 0.011604708 -8.092025e+00 -1.651496e+00 -1.789490e-01
    ## 428 2.388763 16.995964 0.040068342 -6.095964e+00 -1.260992e+00 -2.576278e-01
    ## 429 2.397895 15.460401 0.009330928 -4.460401e+00 -9.075379e-01 -8.807708e-02
    ## 430 2.251292 14.591710 0.013051272 -5.091710e+00 -1.038204e+00 -1.193883e-01
    ## 431 2.674149 19.521301 0.011629749 -5.021301e+00 -1.023079e+00 -1.109774e-01
    ## 432 2.646175 20.179863 0.017067953 -6.079863e+00 -1.242803e+00 -1.637688e-01
    ## 433 2.778819 22.897048 0.012115688 -6.797048e+00 -1.386443e+00 -1.535406e-01
    ## 434 2.660260 18.421273 0.010706183 -4.121273e+00 -8.390187e-01 -8.728233e-02
    ## 435 2.459589 17.527449 0.009789352 -5.827449e+00 -1.186657e+00 -1.179881e-01
    ## 436 2.595255 14.683273 0.016623311 -1.283273e+00 -2.618689e-01 -3.404730e-02
    ## 437 2.261763 16.808124 0.011475787 -7.208124e+00 -1.470170e+00 -1.584037e-01
    ## 438 2.163323 10.955880 0.014715244 -2.255880e+00 -4.599627e-01 -5.621154e-02
    ## 439 2.128232  6.132884 0.027411630  2.267116e+00  4.652634e-01  7.810913e-02
    ## 440 2.549445 11.416311 0.009407449  1.383689e+00  2.813329e-01  2.741630e-02
    ## 441 2.351375 11.507496 0.013355790 -1.007496e+00 -2.052467e-01 -2.387980e-02
    ## 442 2.839078 16.061596 0.011173772  1.038404e+00  2.113104e-01  2.246264e-02
    ## 443 2.912351 17.348578 0.011090243  1.051422e+00  2.139507e-01  2.265719e-02
    ## 444 2.734368 16.864796 0.011336260 -1.464796e+00 -2.981170e-01 -3.192253e-02
    ## 445 2.379546 11.439639 0.009889265 -6.396390e-01 -1.300755e-01 -1.299977e-02
    ## 446 2.468100 13.839840 0.015008280 -2.039840e+00 -4.159590e-01 -5.134518e-02
    ## 447 2.701361 17.029044 0.011315048 -2.129044e+00 -4.333440e-01 -4.635879e-02
    ## 448 2.533697 16.924044 0.010640919 -4.324044e+00 -8.803331e-01 -9.129766e-02
    ## 449 2.646175 16.109785 0.008432290 -2.009785e+00 -4.084664e-01 -3.766759e-02
    ## 450 2.564949 16.663801 0.010289520 -3.663801e+00 -7.456172e-01 -7.602552e-02
    ## 451 2.595255 18.915787 0.013069074 -5.515787e+00 -1.124896e+00 -1.294468e-01
    ## 452 2.721295 18.429469 0.012843845 -3.229469e+00 -6.579950e-01 -7.505457e-02
    ## 453 2.778819 17.234018 0.010350169 -1.134018e+00 -2.306733e-01 -2.359013e-02
    ## 454 2.879198 21.612772 0.022285022 -3.812772e+00 -7.807218e-01 -1.178682e-01
    ## 455 2.701361 17.638322 0.013264601 -2.738322e+00 -5.579758e-01 -6.469372e-02
    ## 456 2.646175 17.613905 0.012374315 -3.513905e+00 -7.158350e-01 -8.012671e-02
    ## 457 2.541602 14.677492 0.010200138 -1.977492e+00 -4.022599e-01 -4.083533e-02
    ## 458 2.602690 15.076490 0.009698583 -1.576490e+00 -3.205881e-01 -3.172619e-02
    ## 459 2.701361 16.990369 0.010623379 -2.090369e+00 -4.253204e-01 -4.407241e-02
    ## 460 2.995732 17.118022 0.010884433  2.881978e+00  5.865602e-01  6.153071e-02
    ## 461 2.797281 19.034939 0.013804423 -2.634939e+00 -5.370443e-01 -6.353861e-02
    ## 462 2.873565 18.828889 0.012187501 -1.128889e+00 -2.298433e-01 -2.553007e-02
    ## 463 2.970414 18.461495 0.011623119  1.038505e+00  2.113789e-01  2.292248e-02
    ## 464 3.005683 21.282681 0.015578090 -1.082681e+00 -2.208138e-01 -2.777747e-02
    ## 465 3.063391 18.951511 0.009314890  2.448489e+00  4.978903e-01  4.827861e-02
    ## 466 2.990720 16.842386 0.011635764  3.057614e+00  6.225706e-01  6.755034e-02
    ## 467 2.944439 16.193874 0.009330718  2.806126e+00  5.706637e-01  5.538261e-02
    ## 468 2.949688 15.680817 0.014238841  3.419183e+00  6.971786e-01  8.379065e-02
    ## 469 2.949688 15.735503 0.010714907  3.364497e+00  6.847934e-01  7.126775e-02
    ## 470 3.000720 17.068749 0.011724001  3.031251e+00  6.172263e-01  6.722692e-02
    ## 471 2.990720 18.477560 0.011544573  1.422440e+00  2.895257e-01  3.128942e-02
    ## 472 2.975530 21.335084 0.015877015 -1.735084e+00 -3.539530e-01 -4.495783e-02
    ## 473 3.144152 20.917950 0.012426227  2.282050e+00  4.647611e-01  5.213324e-02
    ## 474 3.394508 24.531725 0.013790833  5.268275e+00  1.074692e+00  1.270851e-01
    ## 475 2.624669 14.961473 0.012654560 -1.161473e+00 -2.365342e-01 -2.677829e-02
    ## 476 2.587764 15.122362 0.018049405 -1.822362e+00 -3.721735e-01 -5.045823e-02
    ## 477 2.815409 18.933612 0.012111514 -2.233612e+00 -4.548197e-01 -5.035986e-02
    ## 478 2.484907 10.132458 0.013013659  1.867542e+00  3.804286e-01  4.368349e-02
    ## 479 2.681022 17.834130 0.008452506 -3.234130e+00 -6.574833e-01 -6.070447e-02
    ## 480 3.063391 20.732825 0.010447741  6.671752e-01  1.357136e-01  1.394490e-02
    ## 481 3.135494 21.939191 0.015799198  1.060809e+00  2.163768e-01  2.741488e-02
    ## 482 3.165475 25.823302 0.018184294 -2.123302e+00 -4.336846e-01 -5.902109e-02
    ## 483 3.218876 27.377518 0.020114070 -2.377518e+00 -4.861098e-01 -6.964607e-02
    ## 484 3.081910 19.402336 0.019848820  2.397664e+00  4.901645e-01  6.975296e-02
    ## 485 3.025291 17.992117 0.013818446  2.607883e+00  5.315306e-01  6.291866e-02
    ## 486 3.054001 20.817149 0.014551180  3.828511e-01  7.803877e-02  9.482929e-03
    ## 487 2.949688 18.065750 0.011016975  1.034250e+00  2.104483e-01  2.221172e-02
    ## 488 3.025291 19.828789 0.013411153  7.712112e-01  1.571126e-01  1.831791e-02
    ## 489 2.721295 16.315591 0.021016945 -1.115591e+00 -2.281577e-01 -3.342969e-02
    ## 490 1.945910 12.967781 0.024037035 -5.967781e+00 -1.224183e+00 -1.921189e-01
    ## 491 2.091864  8.387842 0.032897146 -2.878419e-01 -5.922623e-02 -1.092338e-02
    ## 492 2.610070 18.401187 0.018707217 -4.801187e+00 -9.816705e-01 -1.355411e-01
    ## 493 3.000720 20.659786 0.018571213 -5.597858e-01 -1.143387e-01 -1.572837e-02
    ## 494 3.081910 21.323337 0.007364136  4.766632e-01  9.680898e-02  8.338378e-03
    ## 495 3.198673 21.331104 0.005115997  3.168896e+00  6.431285e-01  4.611866e-02
    ## 496 3.139833 17.449075 0.005423687  5.650925e+00  1.148079e+00  8.478128e-02
    ## 497 2.980619 14.333492 0.008580367  5.366508e+00  1.091891e+00  1.015789e-01
    ## 498 2.906901 19.749542 0.004517310 -1.449542e+00 -2.939995e-01 -1.980476e-02
    ## 499 3.054001 22.044752 0.004874166 -8.447522e-01 -1.713555e-01 -1.199249e-02
    ## 500 2.862201 19.018293 0.006886040 -1.518293e+00 -3.083136e-01 -2.567308e-02
    ## 501 2.821379 21.163468 0.004408780 -4.363468e+00 -8.855829e-01 -5.893156e-02
    ## 502 3.109061 24.826695 0.016202204 -2.426695e+00 -4.951816e-01 -6.354753e-02
    ## 503 3.025291 23.510828 0.017467114 -2.910828e+00 -5.944189e-01 -7.925554e-02
    ## 504 3.173878 29.088699 0.021353259 -5.188699e+00 -1.062513e+00 -1.569471e-01
    ## 505 3.091042 27.546451 0.019157523 -5.546451e+00 -1.134680e+00 -1.585782e-01
    ## 506 2.476538 23.485511 0.018428878 -1.158551e+01 -2.379657e+00 -3.260640e-01
    ##                D
    ## 1   2.028195e-03
    ## 2   4.088741e-04
    ## 3   6.107368e-04
    ## 4   1.471919e-03
    ## 5   4.677524e-03
    ## 6   6.759395e-04
    ## 7   2.786641e-06
    ## 8   6.430534e-03
    ## 9   7.884576e-03
    ## 10  1.546408e-05
    ## 11  1.642529e-03
    ## 12  3.986340e-04
    ## 13  8.997578e-05
    ## 14  3.571276e-06
    ## 15  1.554570e-04
    ## 16  2.307164e-08
    ## 17  2.186387e-04
    ## 18  2.635863e-07
    ## 19  3.989011e-04
    ## 20  2.572927e-05
    ## 21  3.568493e-05
    ## 22  8.759113e-05
    ## 23  5.430635e-05
    ## 24  1.233331e-05
    ## 25  8.998446e-06
    ## 26  1.786017e-05
    ## 27  1.691165e-05
    ## 28  6.257682e-05
    ## 29  1.711883e-04
    ## 30  2.765536e-05
    ## 31  4.677359e-05
    ## 32  7.551625e-04
    ## 33  1.072403e-03
    ## 34  1.545905e-04
    ## 35  2.282110e-04
    ## 36  7.659923e-04
    ## 37  1.655390e-04
    ## 38  1.275016e-04
    ## 39  1.096226e-04
    ## 40  3.442219e-05
    ## 41  4.412786e-05
    ## 42  1.214886e-04
    ## 43  7.695036e-07
    ## 44  2.985253e-06
    ## 45  9.779221e-05
    ## 46  2.674863e-04
    ## 47  4.061867e-07
    ## 48  5.455502e-05
    ## 49  9.306608e-03
    ## 50  5.576793e-04
    ## 51  2.790014e-05
    ## 52  3.280778e-04
    ## 53  2.027901e-04
    ## 54  3.613277e-08
    ## 55  3.674385e-04
    ## 56  4.340857e-03
    ## 57  8.520961e-05
    ## 58  4.825810e-05
    ## 59  4.780025e-04
    ## 60  2.583942e-06
    ## 61  2.802623e-04
    ## 62  7.682195e-05
    ## 63  2.912226e-05
    ## 64  1.047395e-03
    ## 65  1.548046e-02
    ## 66  6.048498e-03
    ## 67  5.104816e-03
    ## 68  3.180886e-06
    ## 69  9.531506e-06
    ## 70  1.151267e-05
    ## 71  9.669513e-05
    ## 72  6.486025e-06
    ## 73  2.398972e-04
    ## 74  5.513769e-05
    ## 75  3.131128e-04
    ## 76  6.024560e-04
    ## 77  7.723762e-04
    ## 78  5.988572e-04
    ## 79  4.829693e-05
    ## 80  4.855670e-04
    ## 81  1.062722e-05
    ## 82  2.564215e-04
    ## 83  4.603057e-05
    ## 84  1.387026e-04
    ## 85  2.566860e-05
    ## 86  6.703265e-05
    ## 87  8.146163e-06
    ## 88  5.441151e-04
    ## 89  2.295973e-03
    ## 90  3.536976e-04
    ## 91  8.655767e-04
    ## 92  1.226075e-03
    ## 93  1.363203e-03
    ## 94  7.587163e-04
    ## 95  1.581459e-03
    ## 96  8.093429e-05
    ## 97  6.466984e-04
    ## 98  2.730706e-04
    ## 99  4.426501e-03
    ## 100 5.448864e-07
    ## 101 1.137910e-04
    ## 102 1.142677e-05
    ## 103 1.180867e-03
    ## 104 1.636960e-04
    ## 105 2.656229e-04
    ## 106 3.167614e-07
    ## 107 1.373397e-04
    ## 108 1.085738e-04
    ## 109 7.341412e-04
    ## 110 8.980158e-05
    ## 111 1.215743e-07
    ## 112 7.170574e-04
    ## 113 3.220316e-04
    ## 114 3.133837e-04
    ## 115 2.173978e-03
    ## 116 4.454658e-04
    ## 117 2.942607e-04
    ## 118 1.049542e-03
    ## 119 7.066596e-05
    ## 120 2.231140e-04
    ## 121 4.815082e-05
    ## 122 1.894365e-04
    ## 123 3.559131e-05
    ## 124 4.614267e-04
    ## 125 8.997097e-05
    ## 126 1.376881e-05
    ## 127 6.226631e-04
    ## 128 2.217773e-05
    ## 129 4.254174e-04
    ## 130 8.948414e-05
    ## 131 3.999392e-04
    ## 132 1.461539e-04
    ## 133 3.569466e-05
    ## 134 3.117092e-05
    ## 135 1.308016e-05
    ## 136 4.896399e-05
    ## 137 5.916277e-06
    ## 138 9.313013e-04
    ## 139 2.787564e-04
    ## 140 7.489529e-06
    ## 141 1.308736e-04
    ## 142 1.562053e-02
    ## 143 1.772470e-04
    ## 144 1.612116e-03
    ## 145 1.728771e-03
    ## 146 2.292239e-04
    ## 147 1.974344e-03
    ## 148 7.618409e-03
    ## 149 1.160034e-02
    ## 150 6.080128e-05
    ## 151 7.816728e-05
    ## 152 3.557158e-06
    ## 153 3.318066e-03
    ## 154 1.110435e-06
    ## 155 3.656810e-03
    ## 156 6.281642e-03
    ## 157 3.827815e-03
    ## 158 3.415823e-03
    ## 159 3.575502e-03
    ## 160 3.567954e-03
    ## 161 1.937595e-03
    ## 162 1.311457e-02
    ## 163 1.182022e-02
    ## 164 1.183887e-02
    ## 165 5.833589e-04
    ## 166 5.067613e-04
    ## 167 1.309001e-02
    ## 168 1.719434e-04
    ## 169 1.203176e-03
    ## 170 2.038702e-03
    ## 171 3.166802e-03
    ## 172 2.913634e-03
    ## 173 1.997257e-05
    ## 174 1.180336e-03
    ## 175 7.725762e-04
    ## 176 9.384135e-05
    ## 177 1.884078e-04
    ## 178 8.405542e-04
    ## 179 1.134106e-04
    ## 180 1.113106e-03
    ## 181 2.479756e-03
    ## 182 4.567357e-03
    ## 183 1.063658e-03
    ## 184 1.875803e-04
    ## 185 1.271936e-03
    ## 186 1.288849e-03
    ## 187 1.705500e-02
    ## 188 5.235392e-04
    ## 189 1.109931e-03
    ## 190 3.062462e-05
    ## 191 1.674966e-03
    ## 192 3.725552e-05
    ## 193 3.777877e-04
    ## 194 1.455394e-04
    ## 195 6.153642e-04
    ## 196 1.198724e-02
    ## 197 1.857173e-03
    ## 198 1.754722e-03
    ## 199 1.083155e-04
    ## 200 1.648782e-03
    ## 201 5.279141e-05
    ## 202 5.220411e-03
    ## 203 1.943450e-03
    ## 204 1.132170e-02
    ## 205 1.244835e-02
    ## 206 3.821975e-08
    ## 207 1.211600e-05
    ## 208 1.019714e-03
    ## 209 3.723878e-04
    ## 210 3.133841e-03
    ## 211 2.009600e-04
    ## 212 2.682320e-03
    ## 213 2.413775e-04
    ## 214 1.704123e-04
    ## 215 2.549152e-02
    ## 216 5.535537e-06
    ## 217 4.273099e-08
    ## 218 1.429481e-05
    ## 219 4.621560e-07
    ## 220 3.556587e-04
    ## 221 3.498082e-04
    ## 222 2.536807e-04
    ## 223 5.071804e-05
    ## 224 3.056298e-05
    ## 225 4.549089e-03
    ## 226 1.669426e-02
    ## 227 1.488542e-06
    ## 228 9.244096e-06
    ## 229 7.881315e-03
    ## 230 1.990046e-05
    ## 231 1.166301e-05
    ## 232 8.343894e-05
    ## 233 1.513911e-03
    ## 234 1.304281e-02
    ## 235 2.628382e-06
    ## 236 6.441866e-06
    ## 237 6.226147e-05
    ## 238 3.334254e-05
    ## 239 5.689404e-04
    ## 240 6.337141e-04
    ## 241 1.042486e-03
    ## 242 3.208250e-04
    ## 243 9.241076e-05
    ## 244 5.065851e-04
    ## 245 2.297689e-04
    ## 246 3.313944e-03
    ## 247 1.500652e-03
    ## 248 5.936137e-05
    ## 249 7.199345e-04
    ## 250 3.509012e-04
    ## 251 8.940401e-06
    ## 252 3.942594e-06
    ## 253 2.699013e-03
    ## 254 3.735562e-02
    ## 255 9.813736e-04
    ## 256 2.623637e-04
    ## 257 6.525995e-03
    ## 258 8.395403e-03
    ## 259 1.169242e-05
    ## 260 2.131317e-03
    ## 261 4.794946e-05
    ## 262 4.050610e-03
    ## 263 9.819247e-03
    ## 264 1.051552e-03
    ## 265 8.434944e-05
    ## 266 3.310998e-03
    ## 267 7.153881e-07
    ## 268 1.257313e-02
    ## 269 1.734250e-03
    ## 270 1.426717e-04
    ## 271 1.810258e-05
    ## 272 1.075870e-04
    ## 273 5.498496e-04
    ## 274 3.567246e-04
    ## 275 3.927505e-05
    ## 276 1.454019e-04
    ## 277 6.045435e-06
    ## 278 5.011095e-05
    ## 279 3.900564e-05
    ## 280 3.532496e-05
    ## 281 3.872315e-03
    ## 282 1.894900e-04
    ## 283 5.152989e-03
    ## 284 1.184248e-02
    ## 285 6.913140e-08
    ## 286 2.388444e-03
    ## 287 2.649372e-05
    ## 288 4.477497e-04
    ## 289 7.823080e-04
    ## 290 1.118276e-04
    ## 291 4.090210e-03
    ## 292 2.010286e-03
    ## 293 2.349480e-03
    ## 294 2.009899e-04
    ## 295 4.186752e-04
    ## 296 2.203234e-06
    ## 297 2.656872e-06
    ## 298 1.917761e-04
    ## 299 5.065748e-03
    ## 300 1.121894e-03
    ## 301 3.633256e-03
    ## 302 1.422877e-03
    ## 303 1.397156e-04
    ## 304 1.241496e-05
    ## 305 1.009382e-03
    ## 306 5.678131e-05
    ## 307 8.491824e-05
    ## 308 7.170739e-04
    ## 309 1.527700e-03
    ## 310 3.536808e-04
    ## 311 7.410323e-04
    ## 312 1.313424e-03
    ## 313 4.313574e-04
    ## 314 5.071021e-04
    ## 315 9.464902e-05
    ## 316 5.804961e-04
    ## 317 4.604839e-07
    ## 318 4.825234e-05
    ## 319 4.714082e-05
    ## 320 6.443255e-06
    ## 321 4.117663e-05
    ## 322 1.082623e-04
    ## 323 2.067605e-04
    ## 324 1.721274e-05
    ## 325 1.706358e-06
    ## 326 2.740895e-06
    ## 327 2.525980e-05
    ## 328 3.391100e-04
    ## 329 1.051919e-03
    ## 330 9.980283e-04
    ## 331 1.206605e-03
    ## 332 5.968428e-04
    ## 333 9.872913e-04
    ## 334 2.884127e-05
    ## 335 1.198439e-05
    ## 336 1.064319e-04
    ## 337 7.681566e-07
    ## 338 1.558896e-11
    ## 339 4.590381e-05
    ## 340 1.239211e-04
    ## 341 2.208839e-04
    ## 342 9.993022e-05
    ## 343 7.367087e-03
    ## 344 9.454441e-04
    ## 345 1.597228e-04
    ## 346 6.102618e-06
    ## 347 1.576971e-04
    ## 348 9.476320e-04
    ## 349 8.668683e-04
    ## 350 6.782495e-04
    ## 351 5.396024e-05
    ## 352 6.343951e-04
    ## 353 4.888642e-05
    ## 354 1.096612e-02
    ## 355 3.091334e-03
    ## 356 2.941537e-03
    ## 357 2.385401e-04
    ## 358 7.302899e-04
    ## 359 1.929855e-03
    ## 360 1.922553e-03
    ## 361 1.263751e-03
    ## 362 2.760265e-04
    ## 363 2.061744e-03
    ## 364 6.229410e-06
    ## 365 4.343854e-02
    ## 366 1.028149e-01
    ## 367 5.858976e-03
    ## 368 3.764203e-02
    ## 369 1.988862e-01
    ## 370 4.814038e-02
    ## 371 4.216669e-02
    ## 372 4.888676e-02
    ## 373 6.695537e-02
    ## 374 1.278670e-02
    ## 375 4.375558e-02
    ## 376 8.319736e-03
    ## 377 5.540623e-04
    ## 378 2.084171e-03
    ## 379 1.839253e-04
    ## 380 1.350986e-03
    ## 381 5.248091e-02
    ## 382 2.079116e-03
    ## 383 5.496442e-06
    ## 384 5.282681e-05
    ## 385 4.631330e-03
    ## 386 7.519892e-05
    ## 387 3.861244e-03
    ## 388 1.271527e-03
    ## 389 2.407461e-03
    ## 390 3.882871e-05
    ## 391 1.249739e-05
    ## 392 2.165571e-03
    ## 393 1.567966e-04
    ## 394 9.666968e-04
    ## 395 5.676876e-04
    ## 396 1.389655e-03
    ## 397 1.303195e-03
    ## 398 1.406543e-03
    ## 399 1.732538e-05
    ## 400 9.205710e-04
    ## 401 2.070060e-03
    ## 402 3.474506e-03
    ## 403 1.033834e-03
    ## 404 9.057832e-04
    ## 405 5.310645e-04
    ## 406 8.330856e-03
    ## 407 4.572628e-03
    ## 408 5.538782e-03
    ## 409 2.083446e-03
    ## 410 3.922102e-03
    ## 411 6.415451e-03
    ## 412 2.271893e-04
    ## 413 3.697247e-02
    ## 414 2.341041e-03
    ## 415 3.483646e-02
    ## 416 2.028339e-03
    ## 417 6.263195e-03
    ## 418 5.334844e-04
    ## 419 1.008482e-03
    ## 420 5.292792e-03
    ## 421 2.629490e-04
    ## 422 4.473942e-04
    ## 423 4.405351e-04
    ## 424 1.756179e-04
    ## 425 1.396321e-03
    ## 426 6.124525e-04
    ## 427 3.545760e-03
    ## 428 7.365930e-03
    ## 429 8.622584e-04
    ## 430 1.583481e-03
    ## 431 1.368313e-03
    ## 432 2.976762e-03
    ## 433 2.614560e-03
    ## 434 8.469718e-04
    ## 435 1.545531e-03
    ## 436 1.290439e-04
    ## 437 2.781470e-03
    ## 438 3.516397e-04
    ## 439 6.789634e-04
    ## 440 8.367210e-05
    ## 441 6.348290e-05
    ## 442 5.617133e-05
    ## 443 5.714840e-05
    ## 444 1.134355e-04
    ## 445 1.881431e-05
    ## 446 2.934135e-04
    ## 447 2.391839e-04
    ## 448 9.265597e-04
    ## 449 1.579145e-04
    ## 450 6.427831e-04
    ## 451 1.860837e-03
    ## 452 6.266248e-04
    ## 453 6.195069e-05
    ## 454 1.544871e-03
    ## 455 4.656761e-04
    ## 456 7.140661e-04
    ## 457 1.855935e-04
    ## 458 1.120413e-04
    ## 459 2.161759e-04
    ## 460 4.212258e-04
    ## 461 4.492160e-04
    ## 462 7.255876e-05
    ## 463 5.849469e-05
    ## 464 8.589637e-05
    ## 465 2.593730e-04
    ## 466 5.076309e-04
    ## 467 3.412667e-04
    ## 468 7.809044e-04
    ## 469 5.649472e-04
    ## 470 5.027883e-04
    ## 471 1.089818e-04
    ## 472 2.249745e-04
    ## 473 3.024632e-04
    ## 474 1.793954e-03
    ## 475 7.982683e-05
    ## 476 2.833838e-04
    ## 477 2.822410e-04
    ## 478 2.123930e-04
    ## 479 4.099164e-04
    ## 480 2.164944e-05
    ## 481 8.366886e-05
    ## 482 3.876877e-04
    ## 483 5.397823e-04
    ## 484 5.414360e-04
    ## 485 4.404979e-04
    ## 486 1.001179e-05
    ## 487 5.492344e-05
    ## 488 3.735617e-05
    ## 489 1.244089e-04
    ## 490 4.096963e-03
    ## 491 1.328443e-05
    ## 492 2.041415e-03
    ## 493 2.754156e-05
    ## 494 7.740824e-06
    ## 495 2.366048e-04
    ## 496 7.981410e-04
    ## 497 1.146031e-03
    ## 498 4.366121e-05
    ## 499 1.601124e-05
    ## 500 7.336768e-05
    ## 501 3.860485e-04
    ## 502 4.493811e-04
    ## 503 6.988471e-04
    ## 504 2.736222e-03
    ## 505 2.792500e-03
    ## 506 1.170328e-02
